export const TOPICS_BY_CLASS = {
  // ────────────────────────────────────────────── PRIMARY ──────────────────────────────────────────────
  p1: [
    { type: 'equation', topic: 'Addition Equations', subtopics: ['Missing addend ( _ + 2 = 5 )', 'Missing sum ( 3 + 4 = _ )', 'Balance equations ( 2+3 = _+1 )'] },
    { type: 'equation', topic: 'Subtraction Equations', subtopics: ['Missing subtrahend ( 7 - _ = 3 )', 'Missing difference ( 9 - 4 = _ )', 'Missing minuend ( _ - 2 = 4 )'] },
    { type: 'equation', topic: 'Mixed Addition & Subtraction', subtopics: ['Find the missing number (1-10)', 'True or false equations', 'Complete the number sentence'] },
    { type: 'expression', topic: 'Number Expressions', subtopics: ['Write expression for "3 plus 2"', 'Write expression for "5 minus 1"', 'Match words to symbols (+, -, =)'] },
    { type: 'expression', topic: 'Comparing Expressions', subtopics: ['Which is bigger? 2+3 vs 4+1', 'Use >, <, = with simple expressions', 'Order expressions by value'] },
    { type: 'word', topic: 'Addition Word Problems', subtopics: ['Joining groups (e.g., 2 apples + 3 apples)', 'Adding to a set', 'Part-part-whole (unknown total)'] },
    { type: 'word', topic: 'Subtraction Word Problems', subtopics: ['Taking away', 'Comparing differences (how many more?)', 'Finding the missing part'] },
    { type: 'word', topic: 'Multi-step Stories', subtopics: ['Two operations with small numbers', 'Picture-based problems'] },
  ],
  p2: [
    { type: 'equation', topic: 'Addition within 20', subtopics: ['Missing addend ( _ + 8 = 15 )', 'Missing sum ( 12 + 5 = _ )', 'Balance equations ( 9+6 = _+7 )'] },
    { type: 'equation', topic: 'Subtraction within 20', subtopics: ['Missing subtrahend ( 18 - _ = 7 )', 'Missing difference ( 20 - 6 = _ )', 'Missing minuend ( _ - 5 = 9 )'] },
    { type: 'equation', topic: 'Two-digit Addition (no regrouping)', subtopics: ['Missing tens digit', 'Missing ones digit', 'Balance with two-digit numbers'] },
    { type: 'equation', topic: 'Two-digit Subtraction (no regrouping)', subtopics: ['Missing tens digit', 'Missing ones digit', 'Find the error in solved equations'] },
    { type: 'equation', topic: 'Multiplication as Repeated Addition', subtopics: ['2 × 3 = _ + _ + _', 'Find missing factor ( 3 × _ = 12 )', 'Balance equations with multiplication'] },
    { type: 'expression', topic: 'Writing Addition Sentences', subtopics: ['From words: "seven plus eight" → 7+8', 'From pictures (grouped objects)', 'From number bonds'] },
    { type: 'expression', topic: 'Writing Subtraction Sentences', subtopics: ['From words: "fifteen minus four" → 15-4', 'From take-away pictures', 'From comparison bar models'] },
    { type: 'expression', topic: 'Writing Multiplication Sentences', subtopics: ['From repeated addition ( 3+3+3+3 → 4×3 )', 'From equal groups pictures', 'From arrays'] },
    { type: 'expression', topic: 'Evaluating Expressions', subtopics: ['Evaluate 8+9', 'Evaluate 17-5', 'Evaluate 4×2'] },
    { type: 'word', topic: 'Addition Word Problems', subtopics: ['Two-digit plus one-digit', 'Two-digit plus two-digit (no regrouping)', 'Adding three numbers'] },
    { type: 'word', topic: 'Subtraction Word Problems', subtopics: ['Two-digit minus one-digit', 'Two-digit minus two-digit (no regrouping)', 'Comparison problems (how many more/fewer?)'] },
    { type: 'word', topic: 'Multiplication Word Problems', subtopics: ['Equal groups (3 bags of 4 apples)', 'Arrays (rows and columns)', 'Repeated addition contexts'] },
    { type: 'word', topic: 'Two-step Word Problems', subtopics: ['Addition then subtraction', 'Addition then addition', 'Subtraction then addition'] },
  ],
  p3: [
    { type: 'equation', topic: 'Addition within 100', subtopics: ['Missing addend with regrouping', 'Missing sum with regrouping', 'Balance equations with regrouping'] },
    { type: 'equation', topic: 'Subtraction within 100', subtopics: ['Missing subtrahend with regrouping', 'Missing difference with regrouping', 'Missing minuend with regrouping'] },
    { type: 'equation', topic: 'Multiplication Facts (2,3,4,5,10)', subtopics: ['Missing product ( 6 × 4 = _ )', 'Missing factor ( _ × 5 = 25 )', 'Missing factor ( 8 × _ = 32 )'] },
    { type: 'equation', topic: 'Division Facts', subtopics: ['Missing quotient ( 15 ÷ 3 = _ )', 'Missing divisor ( 24 ÷ _ = 6 )', 'Missing dividend ( _ ÷ 4 = 5 )'] },
    { type: 'equation', topic: 'Mixed Operations (+, -, ×, ÷)', subtopics: ['Find missing number in 2-step equations', 'Balance with mixed operations', 'Solve for _ in 3×_ = 12+3'] },
    { type: 'expression', topic: 'Writing Expressions', subtopics: ['From phrases: "a number plus 5" → n+5', 'From phrases: "double a number" → 2×n', 'From real contexts (age, money)'] },
    { type: 'expression', topic: 'Evaluating Expressions', subtopics: ['Evaluate n+7 when n=12', 'Evaluate 3×a when a=6', 'Evaluate 20-b when b=8'] },
    { type: 'expression', topic: 'Simplifying Expressions', subtopics: ['Combine like terms (3a + 2a)', 'Simple distributive: 2×(a+3) = 2a+6', 'Write expressions from area models'] },
    { type: 'word', topic: 'One-step Word Problems', subtopics: ['All four operations within 100', 'Finding the unknown (part-part-whole)', 'Comparison with difference'] },
    { type: 'word', topic: 'Two-step Word Problems', subtopics: ['Addition then multiplication', 'Multiplication then subtraction', 'Division then addition'] },
    { type: 'word', topic: 'Fraction Word Problems', subtopics: ['Unit fractions (1/2, 1/3, 1/4)', 'Finding a fraction of a set (1/3 of 12)', 'Simple fraction addition (same denominator)'] },
    { type: 'word', topic: 'Money Word Problems', subtopics: ['Total cost with bills and coins', 'Change from payment', 'Comparing prices'] },
    { type: 'word', topic: 'Time Word Problems', subtopics: ['Elapsed time (hours only)', 'Start time + duration = end time', 'Reading schedules'] },
  ],
  p4: [
    { type: 'equation', topic: 'Multiplication Facts (6,7,8,9)', subtopics: ['Missing product', 'Missing factor', 'Balance equations with larger factors'] },
    { type: 'equation', topic: 'Multi-digit Multiplication', subtopics: ['2-digit × 1-digit missing number', '3-digit × 1-digit missing number', 'Find the error in multiplication'] },
    { type: 'equation', topic: 'Division with Remainders', subtopics: ['Find quotient and remainder', 'Missing divisor with remainder', 'Missing dividend with remainder'] },
    { type: 'equation', topic: 'Fraction Equations', subtopics: ['Find missing numerator ( 1/4 = _/8 )', 'Find missing denominator ( 3/_ = 6/10 )', 'Compare fractions with missing parts'] },
    { type: 'equation', topic: 'Decimal Equations (tenths, hundredths)', subtopics: ['Missing number in 0.3 + _ = 0.8', 'Missing number in _ - 0.25 = 0.5', 'Balance decimal equations'] },
    { type: 'expression', topic: 'Writing Algebraic Expressions', subtopics: ['"5 more than twice a number" → 2n+5', '"A number decreased by 7" → n-7', '"Product of 8 and a number" → 8n'] },
    { type: 'expression', topic: 'Evaluating with Two Variables', subtopics: ['Evaluate a+b when a=7, b=9', 'Evaluate 2x+y when x=4, y=3', 'Evaluate ab when a=5, b=6'] },
    { type: 'expression', topic: 'Properties of Operations', subtopics: ['Commutative (a+b = b+a, ab=ba)', 'Associative ((a+b)+c = a+(b+c))', 'Distributive (a(b+c) = ab+ac)'] },
    { type: 'expression', topic: 'Simple Factoring', subtopics: ['Factor 2a+4 = 2(a+2)', 'Factor 3x+9 = 3(x+3)', 'Factor 5y-10 = 5(y-2)'] },
    { type: 'word', topic: 'Multiplication Word Problems', subtopics: ['2-digit × 1-digit', '3-digit × 1-digit', 'Multi-step with multiplication'] },
    { type: 'word', topic: 'Division Word Problems', subtopics: ['Division with remainder interpretation (round up/down)', 'Grouping and sharing', 'Multi-step with division'] },
    { type: 'word', topic: 'Fraction Word Problems', subtopics: ['Equivalent fractions', 'Comparing fractions', 'Adding/subtracting fractions (like denominators)'] },
    { type: 'word', topic: 'Decimal Word Problems', subtopics: ['Adding decimals (money contexts)', 'Subtracting decimals (change)', 'Comparing decimals (measurements)'] },
    { type: 'word', topic: 'Area and Perimeter', subtopics: ['Find area (length × width)', 'Find perimeter (2l + 2w)', 'Missing side given area or perimeter'] },
    { type: 'word', topic: 'Angles', subtopics: ['Identifying right, acute, obtuse', 'Finding missing angle on a line (180°)', 'Finding missing angle in a right angle (90°)'] },
  ],
  p5: [
    { type: 'equation', topic: 'Fraction Equations', subtopics: ['Add/subtract fractions (different denominators)', 'Multiply fractions ( × _ = 6/15 )', 'Divide unit fractions by whole numbers ( 1/2 ÷ 3 = _ )'] },
    { type: 'equation', topic: 'Decimal Equations', subtopics: ['Add/subtract decimals to thousandths', 'Multiply decimals (0.3 × 0.4 = _ )', 'Divide decimals by whole numbers ( _ ÷ 4 = 0.25 )'] },
    { type: 'equation', topic: 'Percentage Equations', subtopics: ['Find percentage of a number (10% of 80 = _ )', 'Find the whole ( 20% of _ = 16 )', 'Find the percent ( _% of 50 = 25 )'] },
    { type: 'equation', topic: 'Ratio Equations', subtopics: ['Find missing term ( 2:3 = 4:_ )', 'Find missing term ( _:5 = 6:15 )', 'Scale ratios up/down'] },
    { type: 'equation', topic: 'Order of Operations Equations', subtopics: ['Find missing number with PEMDAS ( 3 + 4 × _ = 19 )', 'Insert parentheses to make true', 'Balance with multiple operations'] },
    { type: 'expression', topic: 'Writing Complex Expressions', subtopics: ['"Three less than twice a number" → 2n-3', '"The sum of a number and 5, divided by 2" → (n+5)/2', '"The product of 7 and the difference of a number and 4" → 7(n-4)'] },
    { type: 'expression', topic: 'Evaluating with Multiple Variables', subtopics: ['Evaluate 2a+3b when a=4, b=5', 'Evaluate 3x-2y when x=7, y=3', 'Evaluate (m+n)/2 when m=12, n=8'] },
    { type: 'expression', topic: 'Simplifying Expressions', subtopics: ['Combine like terms (4a+3b+2a-b)', 'Distributive with negatives (3(x-4) = 3x-12)', 'Simplify (2a+4)/2 = a+2'] },
    { type: 'expression', topic: 'Writing Expressions from Tables', subtopics: ['Input/output tables (linear rules)', 'Find the pattern: 1→4, 2→7, 3→10 → 3n+1', 'Write expression for nth term'] },
    { type: 'word', topic: 'Fraction Word Problems', subtopics: ['Adding/subtracting unlike denominators', 'Multiplying fractions (area of rectangle)', 'Dividing fractions (how many 1/4 cups in 3/4 cup?)'] },
    { type: 'word', topic: 'Decimal Word Problems', subtopics: ['Multiplying decimals (money × quantity)', 'Dividing decimals (splitting bill)', 'Multi-step with decimals'] },
    { type: 'word', topic: 'Percentage Word Problems', subtopics: ['Finding discounts (20% off $50)', 'Finding tax (8% sales tax)', 'Finding tip (15% of bill)'] },
    { type: 'word', topic: 'Ratio Word Problems', subtopics: ['Part-part ratios (3:2 red to blue marbles)', 'Part-whole ratios (2:5 boys to total)', 'Scaling ratios up/down (recipe problems)'] },
    { type: 'word', topic: 'Volume Word Problems', subtopics: ['Volume of rectangular prism (l×w×h)', 'Missing dimension given volume', 'Compare volumes'] },
    { type: 'word', topic: 'Rate Word Problems', subtopics: ['Unit rates (60 km per 2 hours = 30 km/h)', 'Speed = distance/time', 'Price per unit (cost per kg)'] },
  ],
  p6: [
    { type: 'equation', topic: 'One-step Equations', subtopics: ['x + 7 = 12', 'x - 5 = 9', '3x = 18', 'x/4 = 6'] },
    { type: 'equation', topic: 'Two-step Equations', subtopics: ['2x + 3 = 11', '3x - 5 = 10', 'x/2 + 4 = 9', '5 - 2x = 1'] },
    { type: 'equation', topic: 'Equations with Fractions', subtopics: ['½x = 8', '⅔x = 12', 'x/3 + 2 = 7', '(x+4)/2 = 10'] },
    { type: 'equation', topic: 'Equations with Decimals', subtopics: ['x + 0.7 = 3.2', '0.5x = 4.5', '1.2x - 0.8 = 4.0'] },
    { type: 'equation', topic: 'Simple Equation Word Problems', subtopics: ['Translate and solve "A number plus 8 is 15"', 'Translate and solve "Twice a number minus 3 is 11"', 'Translate and solve "One-third of a number is 7"'] },
    { type: 'expression', topic: 'Advanced Algebraic Expressions', subtopics: ['Write: "The quotient of a number and 5, plus 2" → n/5+2', 'Write: "4 less than the product of 7 and a number" → 7n-4', 'Write: "The sum of 3 consecutive numbers" → n+(n+1)+(n+2)'] },
    { type: 'expression', topic: 'Evaluating Complex Expressions', subtopics: ['Evaluate 3(x+y) when x=4, y=6', 'Evaluate x²+2x when x=5', 'Evaluate (a+b)/c when a=15, b=5, c=4'] },
    { type: 'expression', topic: 'Simplifying with Exponents', subtopics: ['Simplify 2a² + 3a²', 'Simplify 4x × 2x', 'Simplify (3y²)(2y³)'] },
    { type: 'expression', topic: 'Expanding and Factoring', subtopics: ['Expand 3(2x+4) = 6x+12', 'Expand x(x+5) = x²+5x', 'Factor 12x+18 = 6(2x+3)', 'Factor x²+4x = x(x+4)'] },
    { type: 'word', topic: 'Ratio and Proportion Word Problems', subtopics: ['Find unknown in proportion (3/4 = x/12)', 'Scale drawing problems (map scale)', 'Unit conversion (cm to m, g to kg)'] },
    { type: 'word', topic: 'Percentage Word Problems', subtopics: ['Percent increase/decrease (price went up 15%)', 'Find original price after discount (sale for $80 after 20% off)', 'Commission and interest (simple)'] },
    { type: 'word', topic: 'Algebra Word Problems', subtopics: ['Consecutive integer problems (sum of 3 consecutive = 24)', 'Age problems (father is 3 times son\'s age)', 'Money problems (total value of coins)'] },
    { type: 'word', topic: 'Geometry Word Problems', subtopics: ['Area of triangles (½×base×height)', 'Area of parallelograms', 'Volume of prisms', 'Missing dimension problems'] },
    { type: 'word', topic: 'Rate and Speed Word Problems', subtopics: ['Average speed (total distance/total time)', 'Distance = rate × time', 'Two travelers (opposite directions, same direction)'] },
    { type: 'word', topic: 'Data and Statistics', subtopics: ['Mean (average) problems (find missing score given mean)', 'Median and mode', 'Range', 'Interpret graphs to solve'] },
  ],
  
  // ──────────────────────────────────────────── JUNIOR SECONDARY ────────────────────────────────────────────
  jss1: [
    { type: 'equation', topic: 'Linear Equations (One Variable)', subtopics: ['Solve ax + b = c (integers)', 'Solve ax - b = c', 'Solve x/a = b', 'Solve x/a + b = c'] },
    { type: 'equation', topic: 'Equations with Brackets', subtopics: ['Solve 2(x+3) = 12', 'Solve 3(2x-1) = 15', 'Solve 4(x+2) + 3 = 23'] },
    { type: 'equation', topic: 'Equations with Fractions', subtopics: ['Solve x/2 + x/3 = 5', 'Solve (x+1)/3 = 4', 'Solve (2x-1)/5 = 3'] },
    { type: 'equation', topic: 'Word Problems to Equations', subtopics: ['Translate stories to ax+b=c', 'Find number problems', 'Consecutive numbers (simple)'] },
    { type: 'expression', topic: 'Algebraic Terminology', subtopics: ['Identify coefficients, constants, variables, terms', 'Like and unlike terms', 'Degree of a term'] },
    { type: 'expression', topic: 'Addition and Subtraction of Expressions', subtopics: ['Add (3x+2) + (4x+5)', 'Subtract (7a+3b) - (2a+b)', 'Simplify with negatives (5x-2) - (3x-4)'] },
    { type: 'expression', topic: 'Multiplication of Expressions', subtopics: ['Multiply monomials (3x × 4y = 12xy)', 'Multiply monomial by binomial (2x(x+3) = 2x²+6x)', 'Multiply binomials (simple: (x+2)(x+3))'] },
    { type: 'expression', topic: 'Substitution', subtopics: ['Evaluate 3x+4y when x=2, y=5', 'Evaluate 2a²+3b when a=4, b=2', 'Evaluate (p+q)/r when p=10, q=5, r=3'] },
    { type: 'inequality', topic: 'Introduction to Inequalities', subtopics: ['Symbols: <, >, ≤, ≥', 'Number line representation', 'Translate "less than" to symbols'] },
    { type: 'inequality', topic: 'Simple Inequalities', subtopics: ['Solve x+3 > 7', 'Solve x-4 ≤ 5', 'Solve 2x > 10', 'Graph solutions on number line'] },
    { type: 'inequality', topic: 'Inequality Word Problems', subtopics: ['"At least" problems', '"No more than" problems', 'Budget constraints'] },
    { type: 'word', topic: 'Number and Operation Problems', subtopics: ['Multi-step word problems (all operations)', 'Order of operations in context', 'Estimation and rounding problems'] },
    { type: 'word', topic: 'Simple Interest', subtopics: ['Calculate interest (I = PRT)', 'Find total amount (A = P + I)', 'Find rate or time given other variables'] },
    { type: 'word', topic: 'Profit and Loss', subtopics: ['Cost price vs selling price', 'Profit = SP - CP', 'Loss = CP - SP', 'Profit percentage = (Profit/CP)×100%'] },
    { type: 'word', topic: 'Geometry Basics', subtopics: ['Types of angles (acute, obtuse, right, reflex, straight)', 'Complementary and supplementary angles', 'Vertically opposite angles'] },
  ],
  jss2: [
    { type: 'equation', topic: 'Linear Equations with Variables on Both Sides', subtopics: ['Solve 2x+3 = x+7', 'Solve 5x-2 = 3x+8', 'Solve 4x+7 = 2x-3', 'Solve with brackets and variables both sides'] },
    { type: 'equation', topic: 'Equations with Algebraic Fractions', subtopics: ['Solve (x/3) = (x/4) + 2', 'Solve (2x/5) - 1 = (x/2)', 'Solve (x+1)/4 = (x-1)/2'] },
    { type: 'equation', topic: 'Forming and Solving Equations', subtopics: ['From geometry contexts (angles, perimeter, area)', 'From age problems (advanced)', 'From mixture contexts'] },
    { type: 'equation', topic: 'Number Base Equations', subtopics: ['Convert numbers to base 10', 'Find unknown base: 23_base = 15_10', 'Addition/subtraction in base 2'] },
    { type: 'expression', topic: 'Laws of Indices', subtopics: ['aᵐ × aⁿ = aᵐ⁺ⁿ', 'aᵐ ÷ aⁿ = aᵐ⁻ⁿ', '(aᵐ)ⁿ = aᵐⁿ', 'a⁰ = 1', 'a⁻ⁿ = 1/aⁿ'] },
    { type: 'expression', topic: 'Simplifying Indicial Expressions', subtopics: ['Simplify 2x³ × 3x⁴', 'Simplify (4y⁵)/(2y²)', 'Simplify (3a²)³', 'Simplify 8x⁶ ÷ 2x²'] },
    { type: 'expression', topic: 'Expanding Binomials', subtopics: ['Expand (x+3)(x+4) = x²+7x+12', 'Expand (x-2)(x+5) = x²+3x-10', 'Expand (2x+1)(x+3) = 2x²+7x+3'] },
    { type: 'expression', topic: 'Factorizing Quadratics (Basic)', subtopics: ['Factor x²+5x+6 = (x+2)(x+3)', 'Factor x²-7x+12 = (x-3)(x-4)', 'Factor x²-9 = (x-3)(x+3) (difference of squares)'] },
    { type: 'inequality', topic: 'Inequalities with Negative Coefficients', subtopics: ['Solve -2x > 6 (reverse sign)', 'Solve 5 - 3x ≤ 11', 'Solve -4x + 7 < -9'] },
    { type: 'inequality', topic: 'Compound Inequalities (AND)', subtopics: ['Solve 2 < x+3 < 7', 'Solve -4 ≤ 2x-1 ≤ 5', 'Graph compound inequalities'] },
    { type: 'inequality', topic: 'Inequality Word Problems (Advanced)', subtopics: ['Minimum/maximum constraints', 'Range of possible values', 'Linear programming intro (simple)'] },
    { type: 'word', topic: 'Number Base Problems', subtopics: ['Convert between bases (2,5,8,10)', 'Addition in binary (carry rules)', 'Subtraction in binary (borrow rules)', 'Real-world applications (computers)'] },
    { type: 'word', topic: 'Ratios and Proportion', subtopics: ['Share amounts in given ratios (divide $120 in 3:2)', 'Increase/decrease in ratio', 'Direct proportion (y ∝ x)', 'Inverse proportion (y ∝ 1/x)'] },
    { type: 'word', topic: 'Speed, Distance, Time', subtopics: ['Find speed given distance and time', 'Find distance given speed and time', 'Find time given distance and speed', 'Average speed for two parts of journey'] },
    { type: 'word', topic: 'Area and Volume Problems', subtopics: ['Area of triangles, trapeziums, parallelograms', 'Circumference and area of circles', 'Volume of cylinder (V = πr²h)', 'Surface area of cuboids'] },
  ],
  jss3: [
    { type: 'equation', topic: 'Simultaneous Linear Equations (Substitution)', subtopics: ['Solve y = 2x, x+y = 9', 'Solve x = y+3, 2x+y = 12', 'Solve y = 3x-2, 2x+3y = 16'] },
    { type: 'equation', topic: 'Simultaneous Linear Equations (Elimination)', subtopics: ['Solve 2x+y=7, 3x-y=8', 'Solve 3x+2y=12, 2x+3y=13', 'Solve with scaling (4x+3y=18, 2x-5y= -4)'] },
    { type: 'equation', topic: 'Quadratic Equations (Factorization)', subtopics: ['Solve x²+5x+6=0', 'Solve x²-7x+12=0', 'Solve x²-9=0', 'Solve 2x²+5x+2=0'] },
    { type: 'equation', topic: 'Quadratic Equations (Completing Square)', subtopics: ['Solve x²+4x-5=0 by completing square', 'Solve x²-6x+8=0', 'Write in form (x+p)² + q'] },
    { type: 'equation', topic: 'Quadratic Equations (Formula)', subtopics: ['Use x = [-b ± √(b²-4ac)]/2a', 'Solve 2x²+3x-5=0', 'Solve x²-4x+2=0 (irrational roots)'] },
    { type: 'expression', topic: 'Factorizing Quadratic Trinomials', subtopics: ['Factor 2x²+7x+3', 'Factor 3x²-10x+8', 'Factor 6x²+5x-6', 'Factor 4x²-12x+9 (perfect square)'] },
    { type: 'expression', topic: 'Difference and Sum of Cubes', subtopics: ['a³ - b³ = (a-b)(a²+ab+b²)', 'a³ + b³ = (a+b)(a²-ab+b²)', 'Factor 8x³ - 27', 'Factor x³ + 64'] },
    { type: 'expression', topic: 'Simplifying Rational Expressions', subtopics: ['Simplify (x²-9)/(x-3)', 'Simplify (x²+5x+6)/(x+2)', 'Simplify (2x²-8)/(x-2)'] },
    { type: 'expression', topic: 'Operations with Algebraic Fractions', subtopics: ['Add (3/x) + (2/x)', 'Subtract (5/(x+1)) - (2/(x+1))', 'Multiply (2x/3) × (4/x²)', 'Divide (x²/2) ÷ (x/4)'] },
    { type: 'inequality', topic: 'Linear Inequalities in Two Variables', subtopics: ['Graph y > 2x+1', 'Graph y ≤ -x+3', 'Shading regions', 'Test points'] },
    { type: 'inequality', topic: 'Quadratic Inequalities', subtopics: ['Solve x²-5x+6 > 0', 'Solve x²-4x+3 ≤ 0', 'Solve 2x²+3x-2 < 0', 'Number line and interval notation'] },
    { type: 'inequality', topic: 'Systems of Linear Inequalities', subtopics: ['Solve system: y > x, y ≤ 2x+1', 'Find feasible region', 'Vertices of region'] },
    { type: 'word', topic: 'Simultaneous Equation Word Problems', subtopics: ['Sum and difference problems (two numbers sum to 20, difference 4)', 'Coin problems (total value $3.50 with 20 coins)', 'Age problems (father and son ages)'] },
    { type: 'word', topic: 'Quadratic Word Problems', subtopics: ['Area problems (length 3 more than width, area 40)', 'Number problems (product of two consecutive numbers)', 'Projectile motion (h = -16t² + vt + s)'] },
    { type: 'word', topic: 'Coordinate Geometry', subtopics: ['Distance between two points (d = √[(x₂-x₁)²+(y₂-y₁)²])', 'Midpoint formula', 'Gradient/slope (m = (y₂-y₁)/(x₂-x₁))', 'Equation of a line (y = mx + c, point-slope form)'] },
    { type: 'word', topic: 'Trigonometry Intro', subtopics: ['Sine, cosine, tangent ratios', 'Find missing side in right triangle', 'Find missing angle', 'Angle of elevation/depression'] },
  ],
  
  // ──────────────────────────────────────────── SENIOR SECONDARY ────────────────────────────────────────────
  ss1: [
    { type: 'equation', topic: 'Quadratic Equations (All Methods)', subtopics: ['Solve by factoring', 'Solve by completing square', 'Solve by quadratic formula', 'Choose best method'] },
    { type: 'equation', topic: 'Nature of Roots', subtopics: ['Discriminant (b²-4ac)', 'Real and distinct (D>0)', 'Real and equal (D=0)', 'No real roots (D<0)', 'Sum and product of roots (α+β = -b/a, αβ = c/a)'] },
    { type: 'equation', topic: 'Equations Reducible to Quadratics', subtopics: ['Solve x⁴ - 5x² + 4 = 0 (substitution)', 'Solve (x²+2x)² - 5(x²+2x) + 6 = 0', 'Solve √(x+3) = x-3 (radical equations)'] },
    { type: 'equation', topic: 'Exponential Equations', subtopics: ['Solve 2ˣ = 8', 'Solve 3²ˣ⁻¹ = 27', 'Solve 4ˣ - 2ˣ⁺¹ = 0', 'Solve 2ˣ × 4ˣ⁺¹ = 8²ˣ'] },
    { type: 'equation', topic: 'Logarithmic Equations', subtopics: ['Solve log₂(x) = 3', 'Solve log₃(x+2) + log₃(x-2) = 1', 'Solve ln(x) + ln(x-1) = ln(6)'] },
    { type: 'expression', topic: 'Polynomials', subtopics: ['Degree, leading coefficient, constant term', 'Addition/subtraction of polynomials', 'Multiplication of polynomials', 'Long division of polynomials'] },
    { type: 'expression', topic: 'Remainder and Factor Theorem', subtopics: ['Find remainder when P(x) ÷ (x-a)', 'Use factor theorem: if P(a)=0 then (x-a) is factor', 'Factor cubic polynomials'] },
    { type: 'expression', topic: 'Partial Fractions (Linear Denominators)', subtopics: ['Decompose (2x+1)/((x+1)(x+2))', 'Decompose (3x-5)/((x-1)(x+3))', 'Decompose (x²+1)/((x-1)(x+2)(x-3))'] },
    { type: 'expression', topic: 'Binomial Expansion', subtopics: ['Expand (a+b)ⁿ for n=1,2,3,4', 'Pascal\'s triangle', 'Binomial theorem: (a+b)ⁿ = Σ C(n,k) aⁿ⁻ᵏ bᵏ', 'Find specific term (r+1th term)'] },
    { type: 'inequality', topic: 'Quadratic Inequalities (Advanced)', subtopics: ['Solve x²+2x-8 > 0', 'Solve -2x²+3x+2 ≤ 0', 'Solve (x-1)(x+3)(x-2) > 0 (cubic)', 'Sign chart method'] },
    { type: 'inequality', topic: 'Rational Inequalities', subtopics: ['Solve (x+2)/(x-3) > 0', 'Solve (x-1)/(x+4) ≤ 0', 'Solve (x²-4)/(x+1) ≥ 0', 'Critical points and test intervals'] },
    { type: 'inequality', topic: 'Absolute Value Inequalities', subtopics: ['Solve |x| < a → -a < x < a', 'Solve |x| > a → x < -a or x > a', 'Solve |2x-3| ≤ 5', 'Solve |x+1| > |x-2|'] },
    { type: 'word', topic: 'Sets and Set Notation', subtopics: ['Union (∪), intersection (∩), complement (A\')', 'Venn diagrams (2 and 3 sets)', 'Number of elements formula: n(A∪B) = n(A)+n(B)-n(A∩B)', 'Word problems with Venn diagrams'] },
    { type: 'word', topic: 'Sequences and Series', subtopics: ['Arithmetic progression: nth term aₙ = a+(n-1)d', 'Sum of AP: Sₙ = n/2[2a+(n-1)d]', 'Geometric progression: nth term aₙ = arⁿ⁻¹', 'Sum of GP: Sₙ = a(rⁿ-1)/(r-1)', 'Sum to infinity (|r|<1): S∞ = a/(1-r)'] },
    { type: 'word', topic: 'Logical Reasoning', subtopics: ['Statements and truth values', 'Negation, conjunction (∧), disjunction (∨)', 'Implication (→), equivalence (↔)', 'Converse, inverse, contrapositive'] },
    { type: 'word', topic: 'Vectors (Intro)', subtopics: ['Column vectors', 'Vector addition and subtraction', 'Scalar multiplication', 'Magnitude (length) of a vector', 'Position vectors'] },
  ],
  ss2: [
    { type: 'equation', topic: 'Simultaneous Equations (One Linear, One Quadratic)', subtopics: ['Solve y = 2x+1, x² + y² = 25', 'Solve y = x-3, xy = 10', 'Solve 2x+y=5, x²-y²=5'] },
    { type: 'equation', topic: 'Exponential and Logarithmic Equations (Advanced)', subtopics: ['Solve 2ˣ⁺¹ = 3ˣ', 'Solve 5²ˣ - 6×5ˣ + 5 = 0', 'Solve log₂(x+3) - log₂(x-1) = 2', 'Solve ln(2x+1) = 3'] },
    { type: 'equation', topic: 'Surd Equations', subtopics: ['Solve √(x+5) = 7', 'Solve √(2x-1) + 3 = 8', 'Solve √(x+3) + √(x-2) = 5', 'Rationalizing denominators'] },
    { type: 'equation', topic: 'Trigonometric Equations', subtopics: ['Solve sin θ = 0.5 for 0°≤θ<360°', 'Solve cos θ = -√3/2', 'Solve tan θ = 1', 'Solve 2 sin²θ - sinθ - 1 = 0'] },
    { type: 'expression', topic: 'Partial Fractions (Repeated and Quadratic Factors)', subtopics: ['Decompose (x+1)/((x-2)²(x+3))', 'Decompose (2x²+3)/((x-1)(x²+4))', 'Decompose with repeated linear factors', 'Decompose with irreducible quadratic'] },
    { type: 'expression', topic: 'Logarithmic Expressions', subtopics: ['Laws: log(ab)=log a+log b, log(a/b)=log a-log b, log(aⁿ)=n log a', 'Change of base: logₐb = log b/log a', 'Simplify log₈16', 'Simplify 2log₃5 - log₃20'] },
    { type: 'expression', topic: 'Trigonometric Identities', subtopics: ['sin²θ + cos²θ = 1', 'tan θ = sinθ/cosθ', '1 + tan²θ = sec²θ', '1 + cot²θ = csc²θ', 'Prove simple identities'] },
    { type: 'expression', topic: 'Complex Numbers (Intro)', subtopics: ['i² = -1', 'Standard form a+bi', 'Addition/subtraction of complex numbers', 'Multiplication of complex numbers', 'Complex conjugates'] },
    { type: 'inequality', topic: 'Absolute Value Equations and Inequalities (Advanced)', subtopics: ['Solve |x-3| = |2x+1|', 'Solve |2x-5| = x+1', 'Solve |x²-4| < 5', 'Solve |x+1| + |x-2| = 4'] },
    { type: 'inequality', topic: 'Polynomial Inequalities', subtopics: ['Solve (x-1)(x+2)(x-3) > 0', 'Solve (x+1)²(x-4) ≤ 0', 'Solve x³ - 2x² - 5x + 6 < 0', 'Solve (x-2)³(x+1) ≥ 0'] },
    { type: 'inequality', topic: 'Linear Programming', subtopics: ['Graph constraints (linear inequalities)', 'Find feasible region', 'Find objective function (max/min)', 'Evaluate at vertices', 'Real-world optimization problems'] },
    { type: 'word', topic: 'Financial Mathematics', subtopics: ['Compound interest: A = P(1+r/n)ⁿᵗ', 'Depreciation (decay)', 'Annuities (future value)', 'Loan amortization (simple)', 'Inflation problems'] },
    { type: 'word', topic: 'Probability', subtopics: ['Theoretical probability (P = favorable/total)', 'Experimental probability', 'Complement rule: P(A\') = 1 - P(A)', 'Addition rule: P(A∪B) = P(A)+P(B)-P(A∩B)', 'Multiplication rule for independent events: P(A∩B) = P(A)×P(B)', 'Conditional probability: P(A|B) = P(A∩B)/P(B)'] },
    { type: 'word', topic: 'Statistics', subtopics: ['Mean for grouped data (using midpoints)', 'Median from grouped frequency table', 'Mode (modal class)', 'Variance and standard deviation (ungrouped)', 'Cumulative frequency and ogive'] },
    { type: 'word', topic: 'Circles and Geometry', subtopics: ['Circle theorems: angle at center twice angle at circumference', 'Angles in same segment', 'Angle in semicircle = 90°', 'Opposite angles of cyclic quadrilateral sum to 180°', 'Tangent-radius perpendicular', 'Tangent from same point equal lengths'] },
  ],
  ss3: [
    { type: 'equation', topic: 'Trigonometric Equations (General Solutions)', subtopics: ['Solve sin θ = sin α → θ = nπ + (-1)ⁿα', 'Solve cos θ = cos α → θ = 2nπ ± α', 'Solve tan θ = tan α → θ = nπ + α', 'Find all solutions in given interval'] },
    { type: 'equation', topic: 'Exponential and Logarithmic Systems', subtopics: ['Solve system: 2ˣ × 4ʸ = 32, 3ˣ⁺ʸ = 81', 'Solve system: log x + log y = 2, x-y=15', 'Solve using substitution and log laws'] },
    { type: 'equation', topic: 'Parametric Equations', subtopics: ['Express y in terms of x given x=f(t), y=g(t)', 'Find Cartesian equation from parametric', 'Parametric equations of lines and circles'] },
    { type: 'equation', topic: 'Differential Equations (Simple)', subtopics: ['Solve dy/dx = k (direct integration)', 'Solve dy/dx = 2x (find y = x²+C)', 'Solve dy/dx = y (exponential growth)', 'Initial conditions to find C'] },
    { type: 'expression', topic: 'Polynomial Division (Long and Synthetic)', subtopics: ['Divide x³+2x²-5x-6 by x+3', 'Divide 2x³-3x²+4x-5 by x-2', 'Synthetic division for linear divisors', 'Find quotient and remainder'] },
    { type: 'expression', topic: 'Rational Functions', subtopics: ['Simplify (x²-4)/(x²-3x+2)', 'Find domain (exclude zeros of denominator)', 'Identify vertical/horizontal asymptotes', 'Sketch basic rational functions'] },
    { type: 'expression', topic: 'Binomial Theorem (General Term)', subtopics: ['General term T_{k+1} = C(n,k) a^{n-k} b^k', 'Find coefficient of x³ in (2x+1)⁵', 'Find term independent of x', 'Binomial approximation (1+x)ⁿ ≈ 1+nx for small x'] },
    { type: 'expression', topic: 'Matrices', subtopics: ['Matrix addition/subtraction', 'Scalar multiplication', 'Matrix multiplication (dimensions matter)', 'Determinant of 2×2 matrix (ad-bc)', 'Inverse of 2×2 matrix (1/(ad-bc) × [d -b; -c a])', 'Solve linear systems using matrices'] },
    { type: 'inequality', topic: 'Linear Programming (Advanced)', subtopics: ['Multiple constraints (3+ inequalities)', 'Integer constraints (integer programming intro)', 'Minimization problems', 'Real-world: production planning, diet problems', 'Sensitivity analysis (basic)'] },
    { type: 'inequality', topic: 'Rational and Radical Inequalities', subtopics: ['Solve (x²-4)/(x+1) < 0', 'Solve √(x+3) > x-1', 'Solve √(2x+5) ≤ x+2', 'Solve (x-3)/√(x+1) ≥ 0'] },
    { type: 'inequality', topic: 'Absolute Value with Quadratics', subtopics: ['Solve |x²-4x+3| < 2', 'Solve |x²-5x+6| ≥ 1', 'Solve |x²-1| = x+1'] },
    { type: 'word', topic: 'Coordinate Geometry (Advanced)', subtopics: ['Equation of circle: (x-h)²+(y-k)² = r²', 'General form: x²+y²+2gx+2fy+c=0', 'Intersection of line and circle', 'Equation of tangent to a circle', 'Length of tangent from external point'] },
    { type: 'word', topic: 'Differentiation (Calculus)', subtopics: ['Derivative as gradient of tangent', 'Derivative of xⁿ: d/dx(xⁿ) = nxⁿ⁻¹', 'Derivative of constant = 0', 'Sum/difference rule', 'Product rule: d/dx(uv)=u\'v+uv\'', 'Quotient rule: d/dx(u/v)=(u\'v-uv\')/v²', 'Chain rule: dy/dx = dy/du × du/dx', 'Find gradient at a point', 'Equation of tangent and normal'] },
    { type: 'word', topic: 'Integration (Calculus)', subtopics: ['Integration as reverse of differentiation', '∫ xⁿ dx = xⁿ⁺¹/(n+1) + C (n≠-1)', '∫ 1/x dx = ln|x| + C', '∫ eˣ dx = eˣ + C', 'Definite integrals (area under curve)', 'Area between curves', 'Applications: displacement from velocity'] },
    { type: 'word', topic: 'Probability Distributions', subtopics: ['Binomial distribution: P(X=k) = C(n,k) p^k q^{n-k}', 'Mean of binomial = np', 'Variance of binomial = npq', 'Normal distribution (intro, empirical rule 68-95-99.7)', 'Standard normal (z-scores)'] },
    { type: 'word', topic: 'Mechanics (Intro)', subtopics: ['Forces (vectors)', 'Resultant force', 'Equilibrium (ΣF=0)', 'Newton\'s second law: F=ma', 'Motion under constant acceleration (SUVAT equations)', 'Projectile motion (simple)'] },
  ],
};