/* ============================================================================
   CHEMISTRY BENCH — the whole of each practical, as PrepBot does it
   ----------------------------------------------------------------------------
   Every practical in waec.js that has no hand-written demonstration in
   prepbot.js has its full method here: from the empty bench to the last
   observation, in the order a careful chemist works, one step at a time.

   A method is a list of lines in the command language PrepBot's hands already
   speak (prepbot.js `command`): the same one the AI tutor uses. A line that
   begins "say " is spoken; every other line is done. The pieces the practical
   needs are laid out first (its `kit`), so a line can name them: vessels are
   lettered in the order the kit lists them, the ones that stand in a rack last.

   These are checked by running every one of them and seeing that every step of
   the practical ticks (scratchpad proc.mjs).
   ========================================================================== */

export const PROCEDURES = {
  // ── volumetric analysis ──
  "titr-strong": [
    "say A titration finds exactly how much acid neutralises a measured amount of alkali.",
    "stand burette A on retort stand",
    "say The burette hangs upright in the clamp. I fill it with the acid, right to the top of its scale.",
    "pour dilute hydrochloric acid into burette A 12 measures",
    "say Now exactly 25.0 cm3 of the alkali goes into the flask. A pipette measures it far better than a beaker could.",
    "pipette sodium hydroxide solution into conical flask B",
    "drip phenolphthalein into conical flask B",
    "say Two drops of phenolphthalein. In the alkali it is pink.",
    "stand conical flask B on retort stand",
    "say The flask stands under the tip of the burette. I run the acid in, quickly at first.",
    "run burette 24",
    "say Still pink, but nearly there. Now one drop at a time, and I stop when the pink just disappears.",
    "run burette 8 drops",
    "say Colourless: that is the end point. The burette reads 25.00 cm3. So 25.00 cm3 of this acid neutralises 25.0 cm3 of the alkali.",
  ],
  "titr-carbonate": [
    "say The same titration, but against sodium carbonate, and with methyl orange as the indicator.",
    "stand burette A on retort stand",
    "pour dilute hydrochloric acid into burette A 12 measures",
    "say The burette is filled with the acid.",
    "pipette sodium carbonate solution into conical flask B",
    "drip methyl orange into conical flask B",
    "say 25.0 cm3 of the carbonate, and two drops of methyl orange. It is yellow in an alkali.",
    "stand conical flask B on retort stand",
    "run burette 24",
    "say It fizzes a little as the acid goes in: that is carbon dioxide. Now drop by drop, until the yellow just turns orange.",
    "run burette 10 drops",
    "say Orange: the end point. Methyl orange is the right indicator for a strong acid against a carbonate. Phenolphthalein would have changed too soon.",
  ],
  // ── qualitative analysis ──
  "cations-naoh": [
    "say Four metal ions, each in its own test tube. Sodium hydroxide tells them apart.",
    "pour copper(II) sulfate solution into test tube A 2 measures",
    "pour iron(II) sulfate solution into test tube B 2 measures",
    "pour iron(III) chloride solution into test tube C 2 measures",
    "pour zinc sulfate solution into test tube D 2 measures",
    "say Copper is blue, iron(II) pale green, iron(III) yellow-brown and zinc has no colour. Now a little sodium hydroxide in each.",
    "pour sodium hydroxide solution into test tube A",
    "say Copper: a pale blue precipitate.",
    "pour sodium hydroxide solution into test tube B",
    "say Iron(II): a dirty green precipitate.",
    "pour sodium hydroxide solution into test tube C",
    "say Iron(III): a reddish-brown precipitate.",
    "pour sodium hydroxide solution into test tube D",
    "say Zinc: a white precipitate. Now the second half of the test: sodium hydroxide in excess.",
    "pour sodium hydroxide solution into test tube D 5 measures",
    "say The white precipitate dissolves. Zinc hydroxide is amphoteric.",
    "pour sodium hydroxide solution into test tube A 4 measures",
    "say The blue precipitate stays, however much is added. Copper(II) hydroxide is insoluble in excess.",
  ],
  "cations-nh3": [
    "say Aqueous ammonia gives precipitates too, but it treats zinc and aluminium differently.",
    "pour copper(II) sulfate solution into test tube A 2 measures",
    "pour zinc sulfate solution into test tube B 2 measures",
    "pour aluminium sulfate solution into test tube C 2 measures",
    "pour aqueous ammonia into test tube A",
    "say Copper: a pale blue precipitate with a little ammonia.",
    "pour aqueous ammonia into test tube A 6 measures",
    "say In excess it dissolves to a deep blue solution. Nothing else does that.",
    "pour aqueous ammonia into test tube B",
    "pour aqueous ammonia into test tube B 7 measures",
    "say Zinc: a white precipitate, which dissolves in excess ammonia.",
    "pour aqueous ammonia into test tube C",
    "pour aqueous ammonia into test tube C 6 measures",
    "say Aluminium: a white precipitate that does NOT dissolve in excess ammonia. That is how zinc and aluminium are told apart.",
  ],
  anions: [
    "say Three tests, for three anions: sulfate, chloride and carbonate.",
    "pour zinc sulfate solution into test tube A 2 measures",
    "pour sodium chloride solution into test tube B 2 measures",
    "pour sodium carbonate solution into test tube C 2 measures",
    "say First the sulfate. Barium chloride solution is added.",
    "pour barium chloride solution into test tube A",
    "say A white precipitate. But a carbonate would give one too, so dilute hydrochloric acid is added.",
    "pour dilute hydrochloric acid into test tube A 2 measures",
    "say It stays. A white precipitate with barium chloride that does not dissolve in acid means a sulfate.",
    "pour silver nitrate solution into test tube B",
    "say The chloride: a white precipitate with silver nitrate.",
    "pour aqueous ammonia into test tube B 4 measures",
    "say It dissolves in excess ammonia. That confirms a chloride.",
    "say Last, the carbonate. Dilute acid goes in, and I test the gas straight away.",
    "pour dilute hydrochloric acid into test tube C",
    "test lighted splint in test tube C",
    "say It fizzes, and the gas puts the flame out. It is carbon dioxide, so the solution holds a carbonate.",
  ],
  ammonium: [
    "say The ammonium ion gives no precipitate. It is found by the gas it gives off.",
    "pour ammonium chloride solution into boiling tube A 2 measures",
    "pour sodium hydroxide solution into boiling tube A 2 measures",
    "say Ammonium chloride with sodium hydroxide. Cold, nothing is seen. So I warm it.",
    "heat boiling tube A",
    "test red litmus paper in boiling tube A",
    "say A gas with a sharp smell, and damp red litmus turns blue at the mouth of the tube. Ammonia is the only common alkaline gas, so the solution held ammonium ions.",
  ],
  unknown: [
    "say X is a solution of one salt. I do the same tests on four portions of it and you work out what it is.",
    "pour sample X into test tube A 2 measures",
    "pour sample X into test tube B 2 measures",
    "pour sample X into test tube C 2 measures",
    "pour sample X into test tube D 2 measures",
    "say Look at its colour first. Now sodium hydroxide, a little and then in excess.",
    "pour sodium hydroxide solution into test tube A",
    "pour sodium hydroxide solution into test tube A 4 measures",
    "say Next aqueous ammonia, a little and then in excess.",
    "pour aqueous ammonia into test tube B",
    "pour aqueous ammonia into test tube B 6 measures",
    "say Barium chloride, then dilute acid: the test for a sulfate.",
    "pour barium chloride solution into test tube C",
    "pour dilute hydrochloric acid into test tube C 2 measures",
    "say And silver nitrate: the test for a chloride.",
    "pour silver nitrate solution into test tube D",
    "say Every observation is in the notebook. Which cation, and which anion? Name them in the guide when it is your turn: your sample will not be the same salt as mine.",
  ],
  // ── gases ──
  "gas-h2": [
    "say Hydrogen is made from zinc and acid, and collected over water.",
    "pour distilled water into trough A 6 measures",
    "upturn gas jar B in trough",
    "say The gas jar is turned over in the trough and stands full of water: no air in it.",
    "fit delivery tube on one-hole stopper",
    "lead to gas jar B",
    "say The delivery tube is ready in its stopper, and leads under the jar. The stopper goes in as soon as the acid is in.",
    "pour zinc granules into conical flask C",
    "pour dilute hydrochloric acid into conical flask C",
    "fit one-hole stopper on conical flask C",
    "wait 2",
    "say Bubbles rise through the water and push it down out of the jar. Now the test.",
    "test lighted splint in gas jar B",
    "say A squeaky pop. The gas is hydrogen. It can be collected over water because it does not dissolve in it.",
  ],
  "gas-co2": [
    "say Carbon dioxide is made from marble chips and dilute acid.",
    "pour marble chips into boiling tube A",
    "pour dilute hydrochloric acid into boiling tube A",
    "say It fizzes at once. The gas has no colour, so it has to be tested.",
    "test lighted splint in boiling tube A",
    "say The flame goes out. Carbon dioxide does not burn, and lets nothing burn in it.",
  ],
  "gas-o2": [
    "say Hydrogen peroxide breaks down to water and oxygen, very slowly. A catalyst makes it quick.",
    "pour hydrogen peroxide solution into boiling tube A 3 measures",
    "say On its own, nothing is seen. Now a little manganese(IV) oxide.",
    "pour manganese(IV) oxide into boiling tube A",
    "test glowing splint in boiling tube A",
    "say Rapid fizzing, and the glowing splint relights. The gas is oxygen. The black powder is still there: a catalyst is not used up.",
  ],
  "gas-nh3": [
    "say Ammonia is lighter than air and very soluble in water. So it is collected in a dry tube, held upside down.",
    "pour ammonium chloride solution into boiling tube A 2 measures",
    "pour sodium hydroxide solution into boiling tube A 2 measures",
    "fit one-hole stopper on boiling tube A",
    "fit delivery tube on one-hole stopper",
    "flip boiling tube B",
    "lead to boiling tube B",
    "say The two solutions are in the first tube, and its delivery tube leads up into the second, which is upside down.",
    "heat boiling tube A",
    "test red litmus paper in boiling tube B",
    "say Warmed, the mixture gives off ammonia. It rises into the upturned tube, and damp red litmus held there turns blue.",
  ],
  // ── separating mixtures ──
  evaporate: [
    "say A dissolved solid is got back from its solution by boiling the water away.",
    "stand evaporating dish A on tripod",
    "pour copper(II) sulfate solution into evaporating dish A 2 measures",
    "say Blue copper(II) sulfate solution in an evaporating dish, on a tripod and gauze.",
    "heat evaporating dish A",
    "say The water has gone, and the solid that was dissolved in it is left in the dish. Only the water left.",
  ],
  distil: [
    "say Distillation gets the WATER back from a solution: it is boiled, and the steam is cooled to a liquid again.",
    "stand distilling flask A on retort stand",
    "fit condenser on distilling flask A",
    "receiver beaker B",
    "say The flask is clamped, the condenser slopes down from its side arm, and a beaker stands under the lower end.",
    "pour copper(II) sulfate solution into distilling flask A 3 measures",
    "say Blue copper(II) sulfate solution goes in. Now I heat it.",
    "heat distilling flask A",
    "say The liquid in the beaker has no colour: it is pure water, the distillate. The copper(II) sulfate stays behind in the flask.",
  ],
  sepfunnel: [
    "say Oil and water do not mix. A separating funnel takes them apart.",
    "stand separating funnel A on retort stand",
    "stand beaker B on retort stand",
    "pour distilled water into separating funnel A 3 measures",
    "pour cooking oil into separating funnel A 2 measures",
    "say Two layers. The oil floats, because it is the less dense. Now I open the tap.",
    "run separating funnel 14",
    "say The water runs out first, and I close the tap just as the last of it goes. Only the oil is left in the funnel.",
  ],
  // ── energy and electricity ──
  heat: [
    "say When an acid meets an alkali, heat is given out. A thermometer shows how much.",
    "pour sodium hydroxide solution into beaker A 3 measures",
    "test thermometer in beaker A",
    "say Sodium hydroxide solution, at room temperature. Now the same amount of acid.",
    "pour dilute hydrochloric acid into beaker A 3 measures",
    "test thermometer in beaker A",
    "say The temperature has gone up. Neutralisation is exothermic: it gives out heat.",
  ],
  displace: [
    "say A more reactive metal pushes a less reactive one out of its solution.",
    "pour copper(II) sulfate solution into test tube A 2 measures",
    "pour silver nitrate solution into test tube B 2 measures",
    "pour zinc sulfate solution into test tube C 2 measures",
    "pour zinc granules into test tube A",
    "say Zinc in copper(II) sulfate: red-brown copper appears, and the blue fades. Zinc is more reactive than copper.",
    "pour copper turnings into test tube B",
    "say Copper in silver nitrate: silvery crystals, and the liquid turns blue. Copper is more reactive than silver.",
    "pour copper turnings into test tube C",
    "say Copper in zinc sulfate: nothing at all. It does not work the other way round. So the order is zinc, copper, silver.",
  ],
  electrolysis: [
    "say Electrolysis: a current is passed through a solution, and something new appears at each rod.",
    "pour copper(II) sulfate solution into beaker A 6 measures",
    "fit carbon electrode on beaker A",
    "fit carbon electrode on beaker A",
    "say Two carbon rods hang in copper(II) sulfate solution, wired to the power pack. I switch on.",
    "current",
    "say Copper coats the negative rod, and bubbles of oxygen come off the positive one.",
    "empty beaker A",
    "pour sodium chloride solution into beaker A 6 measures",
    "say The beaker is emptied, and sodium chloride solution goes in.",
    "current",
    "say This time hydrogen comes off the negative rod, and chlorine, a pale green gas, off the positive one.",
  ],
  flame: [
    "say Some metals colour a flame. A clean wire carries a little of each solution into it.",
    "pour sodium chloride solution into test tube A 2 measures",
    "pour calcium chloride solution into test tube B 2 measures",
    "pour copper(II) sulfate solution into test tube C 2 measures",
    "light burner",
    "flametest test tube A",
    "say Sodium: golden yellow.",
    "flametest test tube B",
    "say Calcium: brick red.",
    "flametest test tube C",
    "say Copper: blue-green. The wire is cleaned between tests, because sodium's yellow hides everything else.",
  ],
};

/** A practical whose demonstration is one of PrepBot's own lessons under another name. */
export const SAME_AS = {};
