// games-data.js — single source of truth for the games hub (home/games/index.html).
//
// To ADD a game: add one entry below. `type` drives which tab it shows under
// ("2d" or "3d"); `premium` drives the badge on its card (actual access is
// enforced by the "games-3d" feature in /utils/features.js + premium-guard.js
// on the game's own page — this list is just what the hub renders).

export const GAMES = [
  {
    id: "free-throw",
    title: "FPV Free Throw",
    category: "Sports",
    type: "3d",
    premium: true,
    href: "/home/games/free-throw/index.html",
    desc: "Aim, shoot, and score with analog aim and a real power meter in first-person basketball.",
  },
  {
    id: "aliens",
    title: "Alien Angle",
    category: "Shooter",
    type: "3d",
    premium: true,
    href: "/home/games/aliens/index.html",
    desc: "Read the angle, aim the cannon, and fire on hidden alien saucers using angular position.",
  },
  {
    id: "chess",
    title: "Grand Chess",
    category: "Strategy",
    type: "3d",
    premium: true,
    href: "/home/games/chess/index.html",
    desc: "Realistic 3D chess with hand-modelled wooden pieces and full legal moves, check and castling.",
  },
  {
    id: "maze",
    title: "3D Maze",
    category: "Adventure",
    type: "3d",
    premium: true,
    href: "/home/games/maze/index.html",
    desc: "Walk a randomly generated maze in first person and find your way to the glowing exit.",
  },
  {
    id: "drone",
    title: "Bearing Courier",
    category: "Simulation",
    type: "3d",
    premium: true,
    href: "/home/games/drone/index.html",
    desc: "Pilot a delivery drone by bearing — read the compass, turn to match, and drop the package.",
  },
  {
    id: "rubiks-cube",
    title: "Rubik's Cube",
    category: "Puzzle",
    type: "3d",
    premium: true,
    href: "/home/games/rubiks-cube/index.html",
    desc: "Solve a realistic 3D Rubik's Cube with the keyboard, twisting faces relative to the front.",
  },
  {
    id: "snakes-ladders",
    title: "Snakes & Ladders",
    category: "Board Game",
    type: "2d",
    premium: false,
    href: "/home/games/snakes-ladders/index.html",
    desc: "Roll the dice, climb the ladders, and dodge the snakes in a classic board game race.",
  },
  {
    id: "block",
    title: "Prime Blockster",
    category: "Puzzle",
    type: "2d",
    premium: false,
    href: "/home/games/block/tetris.html",
    desc: "Stack falling blocks and clear the board while keeping the cleared area a prime number.",
  },
  {
    id: "crossmath",
    title: "Cross Math",
    category: "Puzzle",
    type: "2d",
    premium: false,
    href: "/home/games/crossmath/index.html",
    desc: "Fill in the missing numbers so every row and column of the grid adds up correctly.",
  },
  {
    id: "flip",
    title: "Flip Card Game",
    category: "Memory",
    type: "2d",
    premium: false,
    href: "/home/games/flip/index.html",
    desc: "Flip and match pairs of cards before the clock runs out in this memory challenge.",
  },
  {
    id: "slide",
    title: "Slider Game",
    category: "Puzzle",
    type: "2d",
    premium: false,
    href: "/home/games/slide/game.html",
    desc: "Slide numbered tiles around the board to put them back into perfect order.",
  },
  {
    id: "flappy-bird",
    title: "Math Flappy Bird",
    category: "Arcade",
    type: "2d",
    premium: false,
    href: "/home/games/flappy-bird/flappy.html",
    desc: "Solve quick sums correctly to fly the bird safely through each gap.",
  },
];
