// games-data.js — single source of truth for the games hub (home/games/index.html).
//
// To ADD a game: add one entry below, and put a 2:1 picture of it in play at
// <its folder>/thumb.jpg (800×400) — the card shows it. Every thumb here is a
// screenshot of the game itself, not artwork. `type` drives which tab it shows under
// ("2d" or "3d"); `premium` drives the badge on its card (actual access is
// enforced by the "games-3d" feature in /utils/features.js + premium-guard.js
// on the game's own page — this list is just what the hub renders).
//
// `ready: false` marks a game as still in development — its card renders
// locked (no click-through, "Coming soon" instead of "Play now") until it's
// flipped to true here.

export const GAMES = [
  {
    id: "free-throw",
    title: "FPV Free Throw",
    category: "Sports",
    type: "3d",
    premium: true,
    ready: true,
    href: "/home/games/free-throw/index.html",
    image: "/home/games/free-throw/thumb.jpg",
    desc: "Aim, shoot, and score with analog aim and a real power meter in first-person basketball.",
  },
  {
    id: "aliens",
    title: "Alien Angle",
    category: "Shooter",
    type: "3d",
    premium: true,
    ready: true,
    href: "/home/games/aliens/index.html",
    image: "/home/games/aliens/thumb.jpg",
    desc: "Read the angle, aim the cannon, and fire on hidden alien saucers using angular position.",
  },
  {
    id: "chess",
    title: "Grand Chess",
    category: "Strategy",
    type: "3d",
    premium: true,
    ready: false,
    href: "/home/games/chess/index.html",
    image: "/home/games/chess/thumb.jpg",
    desc: "Realistic 3D chess with hand-modelled wooden pieces and full legal moves, check and castling.",
  },
  {
    id: "maze",
    title: "3D Maze",
    category: "Adventure",
    type: "3d",
    premium: true,
    ready: false,
    href: "/home/games/maze/index.html",
    image: "/home/games/maze/thumb.jpg",
    desc: "Walk a randomly generated maze in first person and find your way to the glowing exit.",
  },
  {
    id: "drone",
    title: "Bearing Courier",
    category: "Simulation",
    type: "3d",
    premium: true,
    ready: false,
    href: "/home/games/drone/index.html",
    image: "/home/games/drone/thumb.jpg",
    desc: "Pilot a delivery drone by bearing — read the compass, turn to match, and drop the package.",
  },
  {
    id: "rubiks-cube",
    title: "Speed Cube",
    category: "Puzzle",
    type: "3d",
    premium: true,
    ready: true,
    href: "/home/games/rubiks-cube/index.html",
    image: "/home/games/rubiks-cube/thumb.jpg",
    desc: "Solve a realistic 3D speed cube with the keyboard, twisting faces relative to the front.",
  },
  {
    id: "snakes-ladders",
    title: "Snakes & Ladders",
    category: "Board Game",
    type: "2d",
    premium: false,
    ready: true,
    href: "/home/games/snakes-ladders/index.html",
    image: "/home/games/snakes-ladders/thumb.jpg",
    desc: "Roll the dice, climb the ladders, and dodge the snakes in a classic board game race.",
  },
  {
    id: "block",
    title: "Prime Blockster",
    category: "Puzzle",
    type: "2d",
    premium: false,
    ready: false,
    href: "/home/games/block/tetris.html",
    image: "/home/games/block/thumb.jpg",
    desc: "Stack falling blocks and clear the board while keeping the cleared area a prime number.",
  },
  {
    id: "crossmath",
    title: "Cross Math",
    category: "Puzzle",
    type: "2d",
    premium: false,
    ready: true,
    href: "/home/games/crossmath/index.html",
    image: "/home/games/crossmath/thumb.jpg",
    desc: "A crossword of sums: place the number tiles so every row and column is true.",
  },
  {
    id: "flip",
    title: "Flip Card Game",
    category: "Memory",
    type: "2d",
    premium: false,
    ready: true,
    href: "/home/games/flip/index.html",
    image: "/home/games/flip/thumb.jpg",
    desc: "Flip two cards and keep the pair when a fraction meets its decimal, percent or angle.",
  },
  {
    id: "slide",
    title: "Slider Game",
    category: "Puzzle",
    type: "2d",
    premium: false,
    ready: true,
    href: "/home/games/slide/game.html",
    image: "/home/games/slide/thumb.jpg",
    desc: "Slide fraction tiles around the board until they sit in order, smallest to largest.",
  },
  {
    id: "flappy-bird",
    title: "Math Flappy Bird",
    category: "Arcade",
    type: "2d",
    premium: false,
    ready: true,
    href: "/home/games/flappy-bird/flappy.html",
    image: "/home/games/flappy-bird/thumb.jpg",
    desc: "Flap through the pipes while you answer sums from a table you choose. One slip ends the flight.",
  },
];
