const chemistryTheory = {
  question1:
    "(a) What is an electrochemical cell? (b) State three differences between an electrochemical cell and an electrolytic cell. (c) Explain briefly what would be observed when powdered zinc is added to a solution of copper (II) tetraoxosulphate (IV) in a beaker. d(i) Write an equation for the reaction in 1(c); (ii) State the type of reaction which took place in 1(c); (e) Name two gases which should be prepared in a fume chamber. (f) Give three factors that favour cracking. (g) Give the reason why noble gases are chemically inert. (h) State four properties of a homologous series. (i) What is global warming? (j) State one cause of global warming.",

  question2:
    "a(i) Define each of the following terms; I. Deliquescence II. efflorescence (ii) Give one example of a substance that undergoes each of the processes in 2a(i) b(i) What is meant by ionization energy? (ii) The second ionization energy value of sodium is greater than the first ionization energy. Briefly give an explanation for this observation. c(i) State Charles' law (ii) Sketch a graph to illustrate Charles' law. (iii) A gas occupies \(150\text{ cm}^3\) at \(21^\circ\text{C}\). What would be its volume if the temperature is raised to \(45^\circ\text{C}\) and the pressure is kept constant? d(i) Write chemical equations to illustrate what happens when each of the following oxides is dissolved in water: I. Sodium oxide; II. Phosphorus(III) oxide; III. Chlorine (VII) oxide; IV. Magnesium oxide (ii) Arrange the solutions in 2d(i) in increasing order of \(pH\).",

  question3:
    "a(i) Write balanced chemical equations for the production of lead(II) chloride by: I. direct combination of constituent elements; II. double decomposition; III. displacement reaction. (ii) State one condition that would increase the rate of reaction for each of the reactions stated in 3a(i). (b) Consider the following chemical reaction in equilibrium: \(2SO_2(g) + O_2(g) \rightleftharpoons 2SO_3(g); \Delta H = \text{positive}\) (i) State two conditions that would increase the yield of \(SO_3(g)\) (ii) If \(60\text{ cm}^3\) of \(SO_2\) reacts with \(40\text{ cm}^3\) of \(O_2\), determine the volume of the residual gas, assuming that the reaction goes to completion in a cylinder. (iii) What is the change in the oxidation number of sulphur in the reaction in 3(b)? (c) Using structural diagrams, explain why cyclopropane is not an isomer of n-propane. (d) A structural organic compound X containing three carbon atoms reacted with butanoic acid in the presence of dilute \(H_2SO_4\) to form a sweet smelling compound Y. (i) Name compounds X and Y. (ii) State the functional group present in X. (iii) Write an equation for the reaction between X and butanoic acid.",

  question4:
    "(a) Write a balanced chemical equation for each of the following reactions: (i) ammonia gas with copper(II) oxide; (ii) ammonia gas with oxygen gas; (iii) aqueous potassium iodide with chlorine gas; (iv) iron with dilute tetraoxosulphate (VI) acid; (v) aqueous lead(II) trioxonitrate (V) with hydrogen chloride gas. b(i) Describe briefly the process involved in the extraction of tin from tin ore. (ii) Mention three uses of hydrogen. (iii) State two physical properties of hydrogen. (c) State the class of oxide to which each of the following compounds belong: (i) \(Na_2O\); (ii) \(ZnO\); (iii) \(SO_2\); (iv) \(CO_2\); (v) \(N_2O\).",

  question5:
    "a(i) Write the chemical formula of alumina. (ii) In the extraction of aluminium, state one compound that is used; I. to obtain alumina from Bauxite II. as solvent for alumina. (iii) Name the electrodes used in the extraction of aluminium. (iv) Give one reason why the extraction of aluminium is expensive. (v) In the extraction of aluminium: I. name the substance liberated at the anode; II. write the equation for the reaction that leads to decrease in the size of the anode. b(i) Give two ions that cause hardness of water. (ii) State two advantages and two disadvantages of hard water. c(i) What is meant by destructive distillation of coal? (ii) Name four products obtained from the destructive distillation of coal. d(i) Name two gases which can be used to demonstrate the fountain experiment. (ii) Give the reason why the gases named in 5d(i) are used.",
};
