export const TOPICS_BY_CLASS = {
  // ────────────────────────────────────────────── PRIMARY ──────────────────────────────────────────────
  p1: [
    { type: 'equation', topic: 'Linear', subtopics: ['Missing addend', 'Missing sum', 'Balance equations'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Missing subtrahend', 'Missing difference', 'Missing minuend'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Mixed missing numbers', 'True or false equations', 'Complete the number sentence'] },
    { type: 'expression', topic: 'Evaluate', subtopics: ['Simple addition expressions', 'Simple subtraction expressions'] },
    { type: 'expression', topic: 'Evaluate', subtopics: ['Compare expressions with >, <, =', 'Order expressions by value'] },
    { type: 'word', topic: 'Addition Word Problems', subtopics: ['Joining groups', 'Adding to a set', 'Part-part-whole (unknown total)'] },
    { type: 'word', topic: 'Subtraction Word Problems', subtopics: ['Taking away', 'Comparing differences', 'Finding the missing part'] },
    { type: 'word', topic: 'Multi-step Stories', subtopics: ['Two operations with small numbers', 'Picture-based problems'] },
  ],
  p2: [
    { type: 'equation', topic: 'Linear', subtopics: ['Missing addend within 20', 'Missing sum within 20', 'Balance equations within 20'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Missing subtrahend within 20', 'Missing difference within 20', 'Missing minuend within 20'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Two-digit addition (no regrouping)', 'Missing tens digit', 'Missing ones digit'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Two-digit subtraction (no regrouping)', 'Missing tens digit', 'Missing ones digit'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Multiplication as repeated addition', 'Missing factor', 'Balance with multiplication'] },
    { type: 'expression', topic: 'Evaluate', subtopics: ['Addition within 20', 'Subtraction within 20', 'Simple multiplication'] },
    { type: 'word', topic: 'Addition Word Problems', subtopics: ['Two-digit plus one-digit', 'Two-digit plus two-digit', 'Adding three numbers'] },
    { type: 'word', topic: 'Subtraction Word Problems', subtopics: ['Two-digit minus one-digit', 'Two-digit minus two-digit', 'Comparison problems'] },
    { type: 'word', topic: 'Multiplication Word Problems', subtopics: ['Equal groups', 'Arrays', 'Repeated addition'] },
    { type: 'word', topic: 'Two-step Word Problems', subtopics: ['Addition then subtraction', 'Addition then addition', 'Subtraction then addition'] },
  ],
  p3: [
    { type: 'equation', topic: 'Linear', subtopics: ['Addition within 100', 'Missing addend with regrouping', 'Balance with regrouping'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Subtraction within 100', 'Missing subtrahend with regrouping', 'Missing minuend with regrouping'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Multiplication facts (2,3,4,5,10)', 'Missing product', 'Missing factor'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Division facts', 'Missing quotient', 'Missing divisor', 'Missing dividend'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Mixed operations', 'Two-step equations', 'Balance with mixed operations'] },
    { type: 'expression', topic: 'Evaluate', subtopics: ['Substitute values into expressions', 'Evaluate with one variable'] },
    { type: 'expression', topic: 'Simplify', subtopics: ['Combine like terms', 'Simple distributive property'] },
    { type: 'word', topic: 'One-step Word Problems', subtopics: ['All four operations within 100', 'Finding the unknown', 'Comparison with difference'] },
    { type: 'word', topic: 'Two-step Word Problems', subtopics: ['Addition then multiplication', 'Multiplication then subtraction', 'Division then addition'] },
    { type: 'word', topic: 'Fraction Word Problems', subtopics: ['Unit fractions', 'Fraction of a set', 'Simple fraction addition'] },
    { type: 'word', topic: 'Money Word Problems', subtopics: ['Total cost', 'Change from payment', 'Comparing prices'] },
    { type: 'word', topic: 'Time Word Problems', subtopics: ['Elapsed time', 'Start time + duration', 'Reading schedules'] },
  ],
  p4: [
    { type: 'equation', topic: 'Linear', subtopics: ['Multiplication facts (6,7,8,9)', 'Missing product', 'Missing factor'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Multi-digit multiplication', '2-digit × 1-digit', '3-digit × 1-digit'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Division with remainders', 'Find quotient and remainder', 'Missing divisor', 'Missing dividend'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Fraction equations', 'Find missing numerator', 'Find missing denominator'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Decimal equations', 'Missing number in addition', 'Missing number in subtraction', 'Balance decimal equations'] },
    { type: 'equation', topic: 'Algebraic Fractions', subtopics: ['Variable divided by number', 'Number divided by variable', 'Variable over number plus constant'] },
    { type: 'expression', topic: 'Simplify', subtopics: ['Commutative property', 'Associative property', 'Distributive property'] },
    { type: 'expression', topic: 'Factorize', subtopics: ['Factor out common factor', 'Factor simple binomials'] },
    { type: 'word', topic: 'Multiplication Word Problems', subtopics: ['2-digit × 1-digit', '3-digit × 1-digit', 'Multi-step with multiplication'] },
    { type: 'word', topic: 'Division Word Problems', subtopics: ['Division with remainder', 'Grouping and sharing', 'Multi-step with division'] },
    { type: 'word', topic: 'Fraction Word Problems', subtopics: ['Equivalent fractions', 'Comparing fractions', 'Adding/subtracting like denominators'] },
    { type: 'word', topic: 'Decimal Word Problems', subtopics: ['Adding decimals', 'Subtracting decimals', 'Comparing decimals'] },
    { type: 'word', topic: 'Area and Perimeter', subtopics: ['Find area', 'Find perimeter', 'Missing side'] },
    { type: 'word', topic: 'Angles', subtopics: ['Identify angles', 'Missing angle on a line', 'Missing angle in right angle'] },
  ],
  p5: [
    { type: 'equation', topic: 'Linear', subtopics: ['Fraction equations', 'Add/subtract unlike denominators', 'Multiply fractions', 'Divide fractions'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Decimal equations', 'Add/subtract decimals', 'Multiply decimals', 'Divide decimals'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Percentage equations', 'Find percentage of a number', 'Find the whole', 'Find the percent'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Ratio equations', 'Find missing term', 'Scale ratios'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Order of operations equations', 'Find missing number', 'Insert parentheses'] },
    { type: 'equation', topic: 'Algebraic Fractions', subtopics: ['Cross multiplication', 'Variable plus number over number', 'Variable minus number over number', 'Number over variable plus number'] },
    { type: 'expression', topic: 'Simplify', subtopics: ['Combine like terms', 'Distributive with negatives', 'Simplify algebraic fractions'] },
    { type: 'word', topic: 'Fraction Word Problems', subtopics: ['Add/subtract unlike denominators', 'Multiply fractions', 'Divide fractions'] },
    { type: 'word', topic: 'Decimal Word Problems', subtopics: ['Multiply decimals', 'Divide decimals', 'Multi-step with decimals'] },
    { type: 'word', topic: 'Percentage Word Problems', subtopics: ['Discounts', 'Sales tax', 'Tip'] },
    { type: 'word', topic: 'Ratio Word Problems', subtopics: ['Part-part ratios', 'Part-whole ratios', 'Scaling ratios'] },
    { type: 'word', topic: 'Volume Word Problems', subtopics: ['Volume of prism', 'Missing dimension', 'Compare volumes'] },
    { type: 'word', topic: 'Rate Word Problems', subtopics: ['Unit rates', 'Speed = distance/time', 'Price per unit'] },
  ],
  p6: [
    { type: 'equation', topic: 'Linear', subtopics: ['One-step equations', 'x + a = b', 'x - a = b', 'ax = b', 'x/a = b'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Two-step equations', 'ax + b = c', 'ax - b = c', 'x/a + b = c'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Equations with fractions', 'Fraction coefficients', 'Fraction constants'] },
    { type: 'equation', topic: 'Linear', subtopics: ['Equations with decimals', 'Decimal coefficients', 'Decimal constants'] },
    { type: 'equation', topic: 'Algebraic Fractions', subtopics: ['Add variable fractions', 'Sum of two fraction expressions', 'Linear expression over number', 'Equal fractions with variable'] },
    { type: 'expression', topic: 'Evaluate', subtopics: ['Evaluate with two variables', 'Evaluate with exponents', 'Evaluate algebraic fractions'] },
    { type: 'expression', topic: 'Simplify', subtopics: ['Simplify with exponents', 'Add and subtract like terms', 'Multiply terms with exponents'] },
    { type: 'expression', topic: 'Expand', subtopics: ['Expand using distributive property', 'Expand binomials'] },
    { type: 'expression', topic: 'Factorize', subtopics: ['Factor out common factor', 'Factor simple quadratics'] },
    { type: 'word', topic: 'Ratio and Proportion', subtopics: ['Find unknown in proportion', 'Scale drawings', 'Unit conversion'] },
    { type: 'word', topic: 'Percentage Word Problems', subtopics: ['Percent increase/decrease', 'Original price after discount', 'Simple interest'] },
    { type: 'word', topic: 'Algebra Word Problems', subtopics: ['Consecutive integers', 'Age problems', 'Coin problems'] },
    { type: 'word', topic: 'Geometry Word Problems', subtopics: ['Area of triangles', 'Area of parallelograms', 'Volume of prisms'] },
    { type: 'word', topic: 'Rate and Speed', subtopics: ['Average speed', 'Distance = rate × time', 'Two travelers'] },
    { type: 'word', topic: 'Data and Statistics', subtopics: ['Mean', 'Median and mode', 'Range'] },
  ],
};