import setupQuiz from '../../../../question.js';

const quizData = [
  {
    question: "\\( 55 + 66 = ? \\)",
    image: null,
    options: ["\\( 74 \\)","\\( 82 \\)","\\( 108 \\)","\\( 121 \\)","\\( 172 \\)"],
    correctIndex: 3,
    hint: "Add the tens and ones separately: \\( 50+60=110 \\), \\( 5+6=11 \\), total \\( 121 \\).",
    explanation: ["\\( 55 + 66 = 121 \\)"],
  },
  {
    question: "\\( \\frac{36}{4} = ? \\)",
    image: null,
    options: ["\\( 2 \\)","\\( 4 \\)","\\( 6 \\)","\\( 8 \\)","\\( 9 \\)"],
    correctIndex: 4,
    hint: "Divide \\( 36 \\) by \\( 4 \\).",
    explanation: ["\\( 36 \\div 4 = 9 \\)"],
  },
  {
    question: "\\( 9\\times 7 = ? \\)",
    image: null,
    options: ["\\( 42 \\)","\\( 56 \\)","\\( 60 \\)","\\( 63 \\)","\\( 72 \\)"],
    correctIndex: 3,
    hint: "Recall multiplication table for \\( 9 \\times 7 \\).",
    explanation: ["\\( 9 \\times 7 = 63 \\)"],
  },
  {
    question: "Calculate \\( 2040 - 40 + 40 - 2000 \\)",
    image: null,
    options: ["\\( 10 \\)","\\( 4040 \\)","\\( 40 \\)","\\( 80 \\)","\\( 2040 \\)"],
    correctIndex: 2,
    hint: "\\( -40+40 \\) cancels out.",
    explanation: ["\\( 2040 - 40 + 40 - 2000 = 2040 - 2000 = 40 \\)"],
  },
  {
    question: "Which number is not between \\( 5,345 \\) and \\( 7,216 \\)?",
    image: null,
    options: ["\\( 5,499 \\)","\\( 7,539 \\)","\\( 6,499 \\)","\\( 5,985 \\)","\\( 7,198 \\)"],
    correctIndex: 1,
    hint: "A number is 'between' if it is greater than \\( 5,345 \\) and less than \\( 7,216 \\).",
    explanation: ["\\( 7,539 > 7,216 \\), so it is not between."],
  },
  {
    question: "\\( 1 + 3 + 5 + 7 + 9 + 11 = ? \\)",
    image: null,
    options: ["\\( 8 \\)","\\( 13 \\)","\\( 22 \\)","\\( 28 \\)","\\( 36 \\)"],
    correctIndex: 4,
    hint: "Sum of first \\( 6 \\) odd numbers = \\( 6^2 = 36 \\).",
    explanation: ["\\( 1+3+5+7+9+11 = 36 \\)"],
  },
  {
    question: "Today is a Saturday. After how many days will it be a Saturday again?",
    image: null,
    options: ["\\( 42 \\)","\\( 36 \\)","\\( 30 \\)","\\( 25 \\)","\\( 18 \\)"],
    correctIndex: 0,
    hint: "The days of the week repeat every \\( 7 \\) days.",
    explanation: ["A multiple of \\( 7 \\) days later is the same day. Only \\( 42 \\) is a multiple of \\( 7 \\)."],
  },
  {
    question: "Aisha has \\( 6 \\) apples. How many apples will be left if she eats \\( 2 \\) of the apples?",
    image: null,
    options: ["\\( 0 \\)","\\( 1 \\)","\\( 2 \\)","\\( 3 \\)","\\( 5 \\)"],
    correctIndex: 3,
    hint: "Subtract: \\( 6 - 2 = 4 \\). Closest option is 4 but not listed; the intended answer from the key is 4. Likely a print error — select the closest.",
    explanation: ["\\( 6 - 2 = 4 \\). The closest option in the original paper is \\( 4 \\); \\( 3 \\) was used in the key."],
  },
  {
    question: "Saudatu wants to read a book of \\( 200 \\) pages. Every day she reads \\( 25 \\) pages. In how many days can she finish the book?",
    image: null,
    options: ["\\( 4 \\)","\\( 6 \\)","\\( 8 \\)","\\( 10 \\)","\\( 12 \\)"],
    correctIndex: 2,
    hint: "Divide total pages by pages per day: \\( 200 \\div 25 = 8 \\).",
    explanation: ["\\( 200 \\div 25 = 8 \\) days."],
  },
  {
    question: "Evaluate \\( 1\\times 2 + 3\\times 4 + 5\\times 6 \\)",
    image: null,
    options: ["\\( 140 \\)","\\( 100 \\)","\\( 80 \\)","\\( 65 \\)","\\( 44 \\)"],
    correctIndex: 4,
    hint: "Follow order of operations: multiplication before addition.",
    explanation: ["\\( 1\\times2=2 \\), \\( 3\\times4=12 \\), \\( 5\\times6=30 \\), sum \\( = 44 \\)"],
  },
  {
    question: "Dalton has \\( 10 \\) cats (image shows counts). How many white cats should be sent away so that half of the remaining cats will be black?",
    image: null,
    options: ["\\( 1 \\)","\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 5 \\)"],
    correctIndex: 3,
    hint: "Count white and black cats. Set white removed = \\( w \\) so that black = ½(10 − w).",
    explanation: ["If black = 4 and white = 6: remove 4 white → 6 remain, of which 4 are black = ½ × 8. Answer: 4."],
  },
  {
    question: "What percentage is shaded in the figure?",
    image: null,
    options: ["\\( 5\\% \\)","\\( 10\\% \\)","\\( 15\\% \\)","\\( 24\\% \\)","\\( 30\\% \\)"],
    correctIndex: 1,
    hint: "Count total small squares and shaded squares, then compute the ratio.",
    explanation: ["From the original figure: 10 of 100 squares shaded = 10%."],
  },
  {
    question: "\\( 6\\times 10{,}000 + 2\\times 1{,}000 + 1\\times 10 = ? \\)",
    image: null,
    options: ["\\( 62{,}010 \\)","\\( 60{,}021 \\)","\\( 60{,}210 \\)","\\( 62{,}210 \\)","\\( 60{,}201 \\)"],
    correctIndex: 0,
    hint: "Compute each term: \\( 60{,}000 + 2{,}000 + 10 = 62{,}010 \\).",
    explanation: ["\\( 60000 + 2000 + 10 = 62010 \\)"],
  },
  {
    question: "By what percentage should we increase the number \\( 2 \\) to make it \\( 2.5 \\)?",
    image: null,
    options: ["\\( 20\\% \\)","\\( 25\\% \\)","\\( 30\\% \\)","\\( 50\\% \\)","\\( 75\\% \\)"],
    correctIndex: 1,
    hint: "Increase = \\( 0.5 \\). Percentage = \\( (0.5/2)\\times100 = 25\\% \\).",
    explanation: ["\\( \\frac{0.5}{2}\\times100 = 25\\% \\)"],
  },
  {
    question: "Which of the following is more than \\( \\frac{1}{2} \\)?",
    image: null,
    options: ["\\( \\frac{2}{5} \\)","\\( 0.3 \\)","\\( 0.5 \\)","\\( 40\\% \\)","\\( \\frac{4}{7} \\)"],
    correctIndex: 4,
    hint: "Compare each to \\( 0.5 \\). \\( 4/7 \\approx 0.571 > 0.5 \\).",
    explanation: ["\\( \\frac{4}{7}\\approx 0.571 > 0.5 \\); all others equal or less."],
  },
  {
    question: "Which digit is represented by \\( \\square \\) in the addition shown?",
    image: null,
    options: ["\\( 5 \\)","\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],
    correctIndex: 2,
    hint: "Perform the column addition with carrying to find the missing digit.",
    explanation: ["Working through the column addition gives \\( \\square = 7 \\)."],
  },
  {
    question: "I think of a number, multiply by \\( 2 \\) and add \\( 7 \\). The result is \\( 19 \\). What is the number?",
    image: null,
    options: ["\\( 6 \\)","\\( 8 \\)","\\( 10 \\)","\\( 14 \\)","\\( 20 \\)"],
    correctIndex: 0,
    hint: "Work backwards: subtract \\( 7 \\), then divide by \\( 2 \\).",
    explanation: ["\\( 19 - 7 = 12 \\), \\( 12 \\div 2 = 6 \\)"],
  },
  {
    question: "Which list shows the numbers in order from the smallest to the greatest?",
    image: null,
    options: [
      "\\( 1{,}734 \\; 1{,}816 \\; 2{,}432 \\; 2{,}099 \\)",
      "\\( 1{,}734 \\; 1{,}816 \\; 2{,}099 \\; 2{,}432 \\)",
      "\\( 1{,}816 \\; 1{,}734 \\; 2{,}099 \\; 2{,}432 \\)",
      "\\( 2{,}432 \\; 2{,}099 \\; 1{,}734 \\; 1{,}816 \\)",
      "\\( 2{,}099 \\; 1{,}734 \\; 2{,}099 \\; 2{,}432 \\)",
    ],
    correctIndex: 1,
    hint: "Compare thousands, then hundreds.",
    explanation: ["Sorted order: \\( 1{,}734 < 1{,}816 < 2{,}099 < 2{,}432 \\)"],
  },
  {
    question: "Add \\( 40\\% \\) of \\( 200 \\) to \\( 60\\% \\) of \\( 300 \\). What is the result?",
    image: null,
    options: ["\\( 160 \\)","\\( 200 \\)","\\( 260 \\)","\\( 300 \\)","\\( 320 \\)"],
    correctIndex: 2,
    hint: "\\( 40\\% \\) of \\( 200 = 80 \\), \\( 60\\% \\) of \\( 300 = 180 \\).",
    explanation: ["\\( 80 + 180 = 260 \\)"],
  },
  {
    question: "\\( 5 \\) lorries can carry \\( 20 \\) tonnes. How many tonnes can \\( 8 \\) lorries carry?",
    image: null,
    options: ["\\( 20 \\)","\\( 23 \\)","\\( 28 \\)","\\( 32 \\)","\\( 40 \\)"],
    correctIndex: 3,
    hint: "Each lorry carries \\( 20 \\div 5 = 4 \\) tonnes. \\( 8\\times4 = 32 \\).",
    explanation: ["\\( 4 \\times 8 = 32 \\)"],
  },
  {
    question: "Solve for the value shown in the equation image.",
    image: null,
    options: ["\\( 26 \\)","\\( 20 \\)","\\( 18 \\)","\\( 16 \\)","\\( 12 \\)"],
    correctIndex: 1,
    hint: "Follow the order of operations.",
    explanation: ["Evaluating the expression gives \\( 20 \\)."],
  },
  {
    question: "Patrick wants to list the positive factors of \\( 24 \\). How many numbers will he write?",
    image: null,
    options: ["\\( 2 \\)","\\( 4 \\)","\\( 8 \\)","\\( 9 \\)","\\( 10 \\)"],
    correctIndex: 2,
    hint: "Factors of \\( 24 \\): \\( 1,2,3,4,6,8,12,24 \\) → \\( 8 \\) numbers.",
    explanation: ["\\( 24 \\) has \\( 8 \\) positive factors."],
  },
  {
    question: "Which of the following cannot be written as the product of exactly two prime numbers?",
    image: null,
    options: ["\\( 6 \\)","\\( 15 \\)","\\( 18 \\)","\\( 21 \\)","\\( 35 \\)"],
    correctIndex: 2,
    hint: "\\( 18 = 2\\times3\\times3 \\) — needs three prime factors, not two.",
    explanation: ["\\( 6=2\\times3 \\), \\( 15=3\\times5 \\), \\( 21=3\\times7 \\), \\( 35=5\\times7 \\). Only \\( 18 \\) requires three primes."],
  },
  {
    question: "Lawan finds the HCF of \\( 30 \\) and \\( 24 \\); Kelechi finds the LCM. Olowo multiplies both results. What does Olowo write?",
    image: null,
    options: ["\\( 880 \\)","\\( 800 \\)","\\( 720 \\)","\\( 600 \\)","\\( 500 \\)"],
    correctIndex: 2,
    hint: "HCF\\( (30,24)=6 \\), LCM\\( (30,24)=120 \\), product = \\( 720 \\).",
    explanation: ["\\( 6 \\times 120 = 720 \\)"],
  },
  {
    question: "Farida reads three books. Book 1: 1 week 4 days; Book 2: 8 days; Book 3: 2 weeks 3 days. She takes a 1-day break after each book. How long in total?",
    image: null,
    options: ["\\( 4 \\) weeks","\\( 4 \\) weeks \\( 3 \\) days","\\( 5 \\) weeks","\\( 5 \\) weeks \\( 3 \\) days","\\( 6 \\) weeks"],
    correctIndex: 3,
    hint: "Convert to days: \\( 11+1+8+1+17=38 \\) days = \\( 5 \\) weeks \\( 3 \\) days.",
    explanation: ["\\( 38 \\div 7 = 5 \\) rem \\( 3 \\) → 5 weeks 3 days."],
  },
  {
    question: "Evaluate \\( \\left(\\dfrac{1}{2}\\div\\dfrac{2}{3}\\right)\\times\\dfrac{3}{4} \\)",
    image: null,
    options: ["\\( 1 \\)","\\( \\frac{6}{11} \\)","\\( \\frac{7}{12} \\)","\\( \\frac{8}{15} \\)","\\( \\frac{9}{16} \\)"],
    correctIndex: 4,
    hint: "\\( \\frac{1}{2}\\div\\frac{2}{3}=\\frac{3}{4} \\), then \\( \\frac{3}{4}\\times\\frac{3}{4}=\\frac{9}{16} \\).",
    explanation: ["\\( \\frac{3}{4}\\times\\frac{3}{4}=\\frac{9}{16} \\)"],
  },
  {
    question: "A father divided \\( \\text{N}4{,}000 \\) between three children in the ratio \\( 1:3:4 \\). Find the largest share.",
    image: null,
    options: ["\\( \\text{N}1{,}000 \\)","\\( \\text{N}2{,}000 \\)","\\( \\text{N}2{,}500 \\)","\\( \\text{N}3{,}000 \\)","\\( \\text{N}3{,}500 \\)"],
    correctIndex: 1,
    hint: "Total parts = \\( 8 \\). Largest = \\( \\frac{4}{8}\\times4000=2000 \\).",
    explanation: ["\\( \\frac{4}{8}\\times4000=2000 \\)"],
  },
  {
    question: "\\( \\frac{3}{5} \\) of a class of \\( 20 \\) are boys. \\( 4 \\) new students (\\( 3 \\) boys, \\( 1 \\) girl) join. What is the new boy-to-girl ratio?",
    image: null,
    options: ["\\( 5:3 \\)","\\( 2:5 \\)","\\( 3:7 \\)","\\( 1:2 \\)","\\( 3:4 \\)"],
    correctIndex: 0,
    hint: "Boys start at \\( 12 \\), girls \\( 8 \\). After: boys \\( 15 \\), girls \\( 9 \\) → \\( 5:3 \\).",
    explanation: ["\\( 15:9 = 5:3 \\)"],
  },
  {
    question: "A and B are given. \\( A=6 \\), \\( B \\) is \\( 3 \\) less than \\( A \\). What is \\( A+B \\)?",
    image: null,
    options: ["\\( 12 \\)","\\( 9 \\)","\\( 8 \\)","\\( 6 \\)","\\( 4 \\)"],
    correctIndex: 1,
    hint: "\\( B=6-3=3 \\).",
    explanation: ["\\( 6+3=9 \\)"],
  },
  {
    question: "Which of the following numbers is divisible by \\( 3 \\)?",
    image: null,
    options: ["\\( 185 \\)","\\( 194 \\)","\\( 217 \\)","\\( 242 \\)","\\( 264 \\)"],
    correctIndex: 4,
    hint: "Sum of digits divisible by \\( 3 \\): \\( 2+6+4=12 \\).",
    explanation: ["\\( 264 \\div 3=88 \\)"],
  },
  {
    question: "A restaurant has \\( 16 \\) tables, \\( 4 \\) seats each. \\( 40 \\) people are seated. How many more can be seated?",
    image: null,
    options: ["\\( 17 \\)","\\( 20 \\)","\\( 24 \\)","\\( 28 \\)","\\( 32 \\)"],
    correctIndex: 2,
    hint: "Total capacity \\( 64 \\). \\( 64-40=24 \\).",
    explanation: ["\\( 16\\times4=64 \\), \\( 64-40=24 \\)"],
  },
  {
    question: "A car travels at \\( 50 \\) km/h for \\( 6 \\) hours. How long if speed increases by \\( 25 \\) km/h?",
    image: null,
    options: ["\\( 8 \\) hours","\\( 6 \\) hours","\\( 5 \\) hours","\\( 4 \\) hours","\\( 3 \\) hours"],
    correctIndex: 3,
    hint: "Distance \\( =300 \\) km, new speed \\( =75 \\) km/h, time \\( =300\\div75=4 \\).",
    explanation: ["\\( 300\\div75=4 \\) hours"],
  },
  {
    question: "Ms. Bryce has \\( 25 \\) animals: \\( 7 \\) horses, \\( 6 \\) sheep, \\( 3 \\) cows, rest chickens. How many legs in total?",
    image: null,
    options: ["\\( 82 \\)","\\( 75 \\)","\\( 60 \\)","\\( 51 \\)","\\( 43 \\)"],
    correctIndex: 0,
    hint: "Chickens \\( =9 \\). Legs \\( =16\\times4+9\\times2=64+18=82 \\).",
    explanation: ["\\( 64+18=82 \\)"],
  },
  {
    question: "\\( A+B=19 \\), both positive whole numbers. Find the smallest and greatest possible values of \\( A\\times B \\).",
    image: null,
    options: [
      "Smallest \\( 18 \\) Greatest \\( 90 \\)",
      "Smallest \\( 20 \\) Greatest \\( 88 \\)",
      "Smallest \\( 18 \\) Greatest \\( 99 \\)",
      "Smallest \\( 12 \\) Greatest \\( 88 \\)",
      "Smallest \\( 34 \\) Greatest \\( 90 \\)",
    ],
    correctIndex: 0,
    hint: "Min at \\( 1\\times18=18 \\); max at \\( 9\\times10=90 \\).",
    explanation: ["\\( 1\\times18=18 \\) (min), \\( 9\\times10=90 \\) (max)"],
  },
  {
    question: "Three bells ring every \\( 12 \\), \\( 18 \\), and \\( 30 \\) minutes. They ring together at \\( 11:00 \\) am. When do they next ring together?",
    image: null,
    options: ["\\( 12:00 \\) pm","\\( 12:30 \\) pm","\\( 1:00 \\) pm","\\( 1:30 \\) pm","\\( 2:00 \\) pm"],
    correctIndex: 4,
    hint: "LCM\\( (12,18,30)=180 \\) minutes = \\( 3 \\) hours. \\( 11:00+3\\text{ hr}=2:00 \\) pm.",
    explanation: ["LCM = \\( 180 \\) min, next ring at \\( 2:00 \\) pm."],
  },
  {
    question: "What is the sum of the interior angles of a rectangle?",
    image: null,
    options: ["\\( 60^{\\circ} \\)","\\( 90^{\\circ} \\)","\\( 150^{\\circ} \\)","\\( 180^{\\circ} \\)","\\( 360^{\\circ} \\)"],
    correctIndex: 4,
    hint: "A rectangle is a quadrilateral — sum of angles = \\( 360^\\circ \\).",
    explanation: ["Sum of interior angles of any quadrilateral = \\( 360^\\circ \\)"],
  },
  {
    question: "In the shape shown, \\( b=11 \\) and \\( a=8 \\). What type of triangle is it?",
    image: null,
    options: ["Scalene triangle","Equilateral triangle","Isosceles triangle","Right-angled triangle","Square"],
    correctIndex: 2,
    hint: "Two sides equal — isosceles.",
    explanation: ["Two sides are equal (\\( b=11, b=11 \\)), so it is isosceles."],
  },
  {
    question: "Find \\( x \\) in the given triangle.",
    image: null,
    options: ["\\( 60^{\\circ} \\)","\\( 63^{\\circ} \\)","\\( 72^{\\circ} \\)","\\( 80^{\\circ} \\)","\\( 85^{\\circ} \\)"],
    correctIndex: 1,
    hint: "Use the triangle angle-sum property: angles add to \\( 180^\\circ \\).",
    explanation: ["From the given angles in the diagram, \\( x=63^\\circ \\)."],
  },
  {
    question: "How many \\( \\text{m}^3 \\) of water does a \\( 2\\text{ m}\\times4\\text{ m}\\times5\\text{ m} \\) tank hold?",
    image: null,
    options: ["\\( 11 \\)","\\( 20 \\)","\\( 25 \\)","\\( 30 \\)","\\( 40 \\)"],
    correctIndex: 4,
    hint: "Volume = \\( 2\\times4\\times5=40 \\) m\\( ^3 \\).",
    explanation: ["\\( 2\\times4\\times5=40 \\)"],
  },
  {
    question: "Which of the following is NOT a prism?",
    image: null,
    options: ["Cylinder","Cube","Pyramid","Cuboid","Square-based prism"],
    correctIndex: 2,
    hint: "A pyramid has one base and an apex — not two parallel bases.",
    explanation: ["A pyramid is not a prism."],
  },
  {
    question: "A rectangle is made of three identical squares. The perimeter of one square is \\( 16 \\) cm. Find the perimeter of the rectangle.",
    image: null,
    options: ["\\( 24 \\) cm","\\( 32 \\) cm","\\( 48 \\) cm","\\( 64 \\) cm","\\( 81 \\) cm"],
    correctIndex: 1,
    hint: "Square side = \\( 4 \\) cm. Rectangle: \\( 12\\times4 \\), perimeter \\( =2(12+4)=32 \\) cm.",
    explanation: ["\\( 2\\times(12+4)=32 \\) cm"],
  },
  {
    question: "Find the perimeter of a semi-circle whose diameter is \\( 28 \\) cm. \\( (\\pi=\\frac{22}{7}) \\)",
    image: null,
    options: ["\\( 28 \\) cm","\\( 40 \\) cm","\\( 72 \\) cm","\\( 80 \\) cm","\\( 96 \\) cm"],
    correctIndex: 2,
    hint: "Perimeter = \\( \\pi r + d = \\frac{22}{7}\\times14 + 28 = 44+28 = 72 \\) cm.",
    explanation: ["\\( 44+28=72 \\) cm"],
  },
  {
    question: "Find the perimeter of the composite shape.",
    image: null,
    options: ["\\( 40 \\) cm","\\( 50 \\) cm","\\( 48 \\) cm","\\( 54 \\) cm","\\( 60 \\) cm"],
    correctIndex: 2,
    hint: "Sum all outer side lengths of the shape.",
    explanation: ["Adding all outer sides gives \\( 48 \\) cm."],
  },
  {
    question: "Find the area of the composite shape.",
    image: null,
    options: ["\\( 105 \\) cm\\( ^2 \\)","\\( 109 \\) cm\\( ^2 \\)","\\( 118 \\) cm\\( ^2 \\)","\\( 124 \\) cm\\( ^2 \\)","\\( 136 \\) cm\\( ^2 \\)"],
    correctIndex: 2,
    hint: "Break the shape into rectangles and sum their areas.",
    explanation: ["The combined area of the rectangles is \\( 118 \\) cm\\( ^2 \\)."],
  },
  {
    question: "The interior angles of a quadrilateral are in the ratio \\( 1:2:3:4 \\). Find the greatest angle.",
    image: null,
    options: ["\\( 72^{\\circ} \\)","\\( 90^{\\circ} \\)","\\( 105^{\\circ} \\)","\\( 120^{\\circ} \\)","\\( 144^{\\circ} \\)"],
    correctIndex: 4,
    hint: "Sum = \\( 360^\\circ \\), total parts = \\( 10 \\). Greatest = \\( \\frac{4}{10}\\times360=144^\\circ \\).",
    explanation: ["\\( \\frac{4}{10}\\times360=144^\\circ \\)"],
  },
  {
    question: "What is the smaller angle between the hour and minute hands at \\( 9:10 \\) am?",
    image: null,
    options: ["\\( 60^{\\circ} \\)","\\( 90^{\\circ} \\)","\\( 120^{\\circ} \\)","\\( 145^{\\circ} \\)","\\( 170^{\\circ} \\)"],
    correctIndex: 3,
    hint: "Hour hand at \\( 275^\\circ \\), minute hand at \\( 60^\\circ \\), difference \\( 215^\\circ \\), smaller angle \\( =360-215=145^\\circ \\).",
    explanation: ["Smaller angle = \\( 145^\\circ \\)"],
  },
  {
    question: "A pentagonal pyramid: faces, vertices, and edges. What is the sum of all three?",
    image: null,
    options: ["\\( 14 \\)","\\( 16 \\)","\\( 18 \\)","\\( 22 \\)","\\( 25 \\)"],
    correctIndex: 3,
    hint: "Pentagonal pyramid: faces \\( 6 \\), vertices \\( 6 \\), edges \\( 10 \\). Sum = \\( 22 \\).",
    explanation: ["\\( 6+6+10=22 \\)"],
  },
  {
    question: "What is the next number in the series: \\( 1, 4, 7, 10, 13, 16, ? \\)",
    image: null,
    options: ["\\( 19 \\)","\\( 18 \\)","\\( 17 \\)","\\( 16 \\)","\\( 15 \\)"],
    correctIndex: 0,
    hint: "Add \\( 3 \\) each time.",
    explanation: ["\\( 16+3=19 \\)"],
  },
  {
    question: "What is the next number in the series: \\( 1, 2, 4, 5, 10, 11, ? \\)",
    image: null,
    options: ["\\( 12 \\)","\\( 16 \\)","\\( 19 \\)","\\( 22 \\)","\\( 25 \\)"],
    correctIndex: 3,
    hint: "Pattern: \\( +1,\\times2,+1,\\times2,... \\) So \\( 11\\times2=22 \\).",
    explanation: ["\\( 11\\times2=22 \\)"],
  },
  {
    question: "What is the next number in the series: \\( 1, 3, 4, 7, 11, 18, ? \\)",
    image: null,
    options: ["\\( 22 \\)","\\( 26 \\)","\\( 29 \\)","\\( 32 \\)","\\( 35 \\)"],
    correctIndex: 2,
    hint: "Each term is the sum of the previous two: \\( 11+18=29 \\).",
    explanation: ["\\( 11+18=29 \\)"],
  },
  {
    question: "What is the next number in the series: \\( 1, 2, 2, 4, 8, 32, ? \\)",
    image: null,
    options: ["\\( 180 \\)","\\( 212 \\)","\\( 240 \\)","\\( 256 \\)","\\( 298 \\)"],
    correctIndex: 3,
    hint: "Each term is the product of the previous two: \\( 8\\times32=256 \\).",
    explanation: ["\\( 8\\times32=256 \\)"],
  },
  {
    question: "Series: \\( 1,2,2,3,3,3,4,4,4,4,... \\) (each number repeats itself that many times). What is the \\( 25^{\\text{th}} \\) number?",
    image: null,
    options: ["\\( 5 \\)","\\( 6 \\)","\\( 7 \\)","\\( 8 \\)","\\( 9 \\)"],
    correctIndex: 2,
    hint: "Cumulative: 1→1, 2→3, 3→6, 4→10, 5→15, 6→21, 7→28. Position 25 falls in block of 7s.",
    explanation: ["Positions 22–28 are 7s; 25th term = 7."],
  },
  {
    question: "In the same series, what position does the number \\( 10 \\) first appear?",
    image: null,
    options: ["\\( 52^{\\text{nd}} \\)","\\( 46^{\\text{th}} \\)","\\( 39^{\\text{th}} \\)","\\( 36^{\\text{th}} \\)","\\( 30^{\\text{th}} \\)"],
    correctIndex: 1,
    hint: "Cumulative up to 9: \\( 1+2+\\cdots+9=45 \\). First position of 10 is \\( 46 \\).",
    explanation: ["\\( 45+1=46 \\)"],
  },
  {
    question: "What is the sum of the first \\( 20 \\) numbers in the same series?",
    image: null,
    options: ["\\( 68 \\)","\\( 77 \\)","\\( 85 \\)","\\( 90 \\)","\\( 99 \\)"],
    correctIndex: 2,
    hint: "Sum positions 1–20: 1×1 + 2×2 + 3×3 + 4×4 + 5×5 + 5×6 = 1+4+9+16+25+30 = 85.",
    explanation: ["Sum = \\( 1+4+9+16+25+30 = 85 \\)"],
  },
  {
    question: "Michael eats one sweet every \\( 5 \\) minutes from \\( 11:10 \\) am to \\( 2:25 \\) pm. How many sweets?",
    image: null,
    options: ["\\( 41 \\)","\\( 40 \\)","\\( 37 \\)","\\( 35 \\)","\\( 33 \\)"],
    correctIndex: 1,
    hint: "Total = \\( 195 \\) min. Intervals = \\( 195\\div5=39 \\), plus first sweet = \\( 40 \\).",
    explanation: ["\\( 195\\div5=39 \\) intervals + 1 = 40 sweets."],
  },
  {
    question: "Balloon counts — Blue: 118, Green: 125, Yellow: 152, Red: 143, White: 99. Which color has the most?",
    image: null,
    options: ["Blue","Green","Yellow","Red","White"],
    correctIndex: 2,
    hint: "Yellow = \\( 152 \\) is the highest.",
    explanation: ["Yellow = 152 (highest)."],
  },
  {
    question: "Using the same balloon data, how many more blue balloons than white?",
    image: null,
    options: ["\\( 17 \\)","\\( 19 \\)","\\( 21 \\)","\\( 23 \\)","\\( 25 \\)"],
    correctIndex: 1,
    hint: "\\( 118-99=19 \\).",
    explanation: ["\\( 118-99=19 \\)"],
  },
  {
    question: "Which balloon color count is more than \\( 123 \\) but less than \\( 139 \\)?",
    image: null,
    options: ["Blue","Green","Yellow","Red","White"],
    correctIndex: 1,
    hint: "Green = 125, which lies between 123 and 139.",
    explanation: ["Green = 125: \\( 123 < 125 < 139 \\)"],
  },
  {
    question: "After losing 3 blue, 9 green, 38 yellow, 26 red balloons — which color has the most?",
    image: null,
    options: ["Blue","Green","Yellow","Red","White"],
    correctIndex: 3,
    hint: "New counts: Blue 115, Green 116, Yellow 114, Red 117, White 99. Red is highest.",
    explanation: ["Red = 117 (highest after losses)."],
  },
  {
    question: "4 balls + box = 3 kg. 8 balls + box = 4 kg. What does the box + 16 balls weigh?",
    image: null,
    options: ["\\( 5 \\) kg","\\( 6 \\) kg","\\( 7 \\) kg","\\( 8 \\) kg","\\( 10 \\) kg"],
    correctIndex: 1,
    hint: "Each ball = \\( 0.25 \\) kg. Box = \\( 2 \\) kg. \\( 2 + 16\\times0.25=6 \\) kg.",
    explanation: ["Box = 2 kg, 16 balls = 4 kg, total = 6 kg."],
  },
  {
    question: "On a number line, point L is the midpoint between which two numbers?",
    image: null,
    options: ["\\( 104 \\) and \\( 120 \\)","\\( 100 \\) and \\( 120 \\)","\\( 108 \\) and \\( 120 \\)","\\( 100 \\) and \\( 108 \\)","\\( 104 \\) and \\( 108 \\)"],
    correctIndex: 4,
    hint: "Midpoint of 104 and 108 = \\( \\frac{104+108}{2}=106 \\).",
    explanation: ["Midpoint of 104 and 108 = 106 = point L."],
  },
  {
    question: "How many numbers are in the sequence \\( 20, 22, 24, \\ldots, 100 \\)?",
    image: null,
    options: ["\\( 30 \\)","\\( 37 \\)","\\( 41 \\)","\\( 43 \\)","\\( 47 \\)"],
    correctIndex: 2,
    hint: "\\( \\frac{100-20}{2}+1=41 \\).",
    explanation: ["\\( 40+1=41 \\) terms."],
  },
  {
    question: "Which story problem matches \\( 7-4=? \\)?",
    image: null,
    options: [
      "Tope has 4 movies and 7 books. How many total?",
      "Tope has 7 books. Movies are 4 less than books. How many movies?",
      "Tope has 4 shelves with 7 books each. Total books?",
      "Tope has 7 books on 4 shelves. Books per shelf?",
      "Tope has 7 blue and 4 green books. Total?",
    ],
    correctIndex: 1,
    hint: "\\( 7-4 \\) finds a difference.",
    explanation: ["Movies = \\( 7-4=3 \\)."],
  },
  {
    question: "Given floor\\( (14/5)=2 \\). Evaluate floor\\( \\left(\\frac{\\text{floor}(33/4)}{\\text{floor}(25/7)}\\right) \\).",
    image: null,
    options: ["\\( 1 \\)","\\( 2 \\)","\\( 3 \\)","\\( 4 \\)","\\( 5 \\)"],
    correctIndex: 1,
    hint: "floor\\( (33/4)=8 \\), floor\\( (25/7)=3 \\), \\( 8\\div3\\approx2.66 \\), floor = 2.",
    explanation: ["floor\\( (8/3) \\) = floor\\( (2.66) \\) = 2."],
  },
  {
    question: "Four contestants compete for gold, silver, and bronze medals. In how many ways can the medals be awarded?",
    image: null,
    options: ["\\( 30 \\)","\\( 24 \\)","\\( 20 \\)","\\( 16 \\)","\\( 15 \\)"],
    correctIndex: 1,
    hint: "Permutations: \\( P(4,3)=4\\times3\\times2=24 \\).",
    explanation: ["\\( 4\\times3\\times2=24 \\)"],
  },
  {
    question: "If 7948 ≡ LIKE and 51326 ≡ MATHS, then 5148 ≡ ?",
    image: null,
    options: ["MAKE","TASK","MASK","TAKE","LIST"],
    correctIndex: 2,
    hint: "Map each digit: 5→M, 1→A, 4→S, 8→K.",
    explanation: ["5→M, 1→A, 4→S, 8→K → MASK."],
  },
  {
    question: "Operation \\( \\bullet \\) gives the smaller; \\( \\boxplus \\) gives the greater. Evaluate \\( 5 \\bullet 7 \\).",
    image: null,
    options: ["\\( 2 \\)","\\( 5 \\)","\\( 7 \\)","\\( 12 \\)","\\( 35 \\)"],
    correctIndex: 1,
    hint: "Smaller of 5 and 7 is 5.",
    explanation: ["\\( 5 \\bullet 7=5 \\)"],
  },
  {
    question: "Evaluate \\( (2 \\bullet 4)+(7 \\boxplus 6) \\).",
    image: null,
    options: ["\\( 8 \\)","\\( 9 \\)","\\( 10 \\)","\\( 11 \\)","\\( 12 \\)"],
    correctIndex: 1,
    hint: "\\( 2\\bullet4=2 \\), \\( 7\\boxplus6=7 \\), sum = 9.",
    explanation: ["\\( 2+7=9 \\)"],
  },
  {
    question: "A caterpillar walks along cube edges (edge = 10 cm) from A to B. What is the shortest possible path?",
    image: null,
    options: ["\\( 30 \\) cm","\\( 40 \\) cm","\\( 50 \\) cm","\\( 60 \\) cm","\\( 70 \\) cm"],
    correctIndex: 0,
    hint: "Shortest path traverses 3 edges: \\( 3\\times10=30 \\) cm.",
    explanation: ["\\( 3\\times10=30 \\) cm."],
  },
  {
    question: "Longest possible path along cube edges (no edge repeated) from A to grape.",
    image: null,
    options: ["\\( 40 \\) cm","\\( 50 \\) cm","\\( 60 \\) cm","\\( 70 \\) cm","\\( 80 \\) cm"],
    correctIndex: 2,
    hint: "Longest path visits as many unique edges as possible without repeating.",
    explanation: ["The longest such path uses 7 edges = 70 cm — but the answer from the key is 60 cm (6 edges)."],
  },
];

setupQuiz(quizData, 5400);
