import setupQuiz from '../../../../question.js';

const quizData = [
  {
    question: "Which numeral has the digit \\( 2 \\) in the millions place?",
    image: null,
    options: [
      "\\( 1,807,629 \\)",
      "\\( 82,531,044 \\)",
      "\\( 28,162,751 \\)",
      "\\( 8,629,794,312 \\)",
      "\\( 1,234,567,123 \\)",
    ],
    correctIndex: 1,
    hint: "The millions place is the \\( 7 \\)th digit from the right. Identify which number has the digit \\( 2 \\) in that position.",
    explanation: [
      "In \\( 82,531,044 \\), the digits from left to right are: \\( 8 \\) (ten-millions), \\( 2 \\) (millions), \\( 5 \\) (hundred-thousands), etc.",
      "Therefore, the digit \\( 2 \\) is in the millions place.",
    ],
  },
  {
    question: "Which of the following shows the prime factorization of \\( 120 \\)?",
    image: null,
    options: [
      "\\( 2\\times 6\\times 20 \\)",
      "\\( 2\\times 3\\times 20 \\)",
      "\\( 2\\times 3\\times 4\\times 5 \\)",
      "\\( 2\\times 2\\times 3\\times 5\\times 5 \\)",
      "None of the above",
    ],
    correctIndex: 4,
    hint: "Prime factorization means writing the number as a product of only prime numbers.",
    explanation: [
      "The prime factorization of \\( 120 \\) is \\( 2^3 \\times 3 \\times 5 = 2 \\times 2 \\times 2 \\times 3 \\times 5 \\).",
      "None of the options show \\( 2 \\times 2 \\times 2 \\times 3 \\times 5 \\), so the answer is 'None of the above'.",
    ],
  },
  {
    question: "Which fraction is equivalent to \\( \\frac{3}{8} \\)?",
    image: null,
    options: [
      "\\( \\frac{8}{11} \\)",
      "\\( \\frac{9}{16} \\)",
      "\\( \\frac{9}{24} \\)",
      "\\( \\frac{5}{16} \\)",
      "None of the above",
    ],
    correctIndex: 2,
    hint: "Multiply or divide both numerator and denominator by the same number to find an equivalent fraction.",
    explanation: [
      "\\( \\frac{3}{8} = \\frac{3 \\times 3}{8 \\times 3} = \\frac{9}{24} \\).",
      "\\( \\frac{9}{24} \\) simplifies back to \\( \\frac{3}{8} \\), confirming equivalence.",
    ],
  },
  {
    question: "Which list shows all the common factors of \\( 24 \\), \\( 36 \\) and \\( 48 \\)?",
    image: null,
    options: [
      "\\( 1, 2, 3, 4, 6, 12 \\)",
      "\\( 2, 6, 12 \\)",
      "\\( 1, 2, 3 \\)",
      "\\( 1, 3, 4, 6, 8 \\)",
      "None of the above",
    ],
    correctIndex: 0,
    hint: "List all factors of each number, then find the intersection.",
    explanation: [
      "Factors of \\( 24 \\): \\( 1, 2, 3, 4, 6, 8, 12, 24 \\).",
      "Factors of \\( 36 \\): \\( 1, 2, 3, 4, 6, 9, 12, 18, 36 \\).",
      "Factors of \\( 48 \\): \\( 1, 2, 3, 4, 6, 8, 12, 16, 24, 48 \\).",
      "Common factors: \\( 1, 2, 3, 4, 6, 12 \\).",
    ],
  },
  {
    question: "Which fraction does the shaded part of the figure represent?",
    image: null,
    options: [
      "\\( \\frac{8}{22} \\)",
      "\\( \\frac{2}{5} \\)",
      "\\( \\frac{3}{5} \\)",
      "\\( \\frac{12}{20} \\)",
      "None of the above",
    ],
    correctIndex: 1,
    hint: "Count the total number of equal parts and the number of shaded parts.",
    explanation: [
      "If \\( 8 \\) out of \\( 20 \\) equal parts are shaded, that simplifies to \\( \\frac{8}{20} = \\frac{2}{5} \\).",
    ],
  },
  {
    question: "Which of these is a prime number?",
    image: null,
    options: [
      "\\( 49 \\)",
      "\\( 59 \\)",
      "\\( 63 \\)",
      "\\( 91 \\)",
      "\\( 57 \\)",
    ],
    correctIndex: 1,
    hint: "A prime number has exactly two distinct factors: \\( 1 \\) and itself.",
    explanation: [
      "\\( 49 = 7 \\times 7 \\) (not prime).",
      "\\( 59 \\) has no divisors other than \\( 1 \\) and \\( 59 \\) (prime).",
      "\\( 63 = 7 \\times 9 \\) (not prime).",
      "\\( 91 = 7 \\times 13 \\) (not prime).",
      "\\( 57 = 3 \\times 19 \\) (not prime).",
    ],
  },
  {
    question: "Royce has a bag with \\( 8 \\) red marbles, \\( 4 \\) blue marbles, \\( 5 \\) green marbles, and \\( 9 \\) yellow marbles all the same size. If he pulls out \\( 1 \\) marble without looking, which color is he most likely to choose?",
    image: null,
    options: ["red", "blue", "green", "yellow", "none of the above"],
    correctIndex: 3,
    hint: "The color with the highest number of marbles has the greatest probability.",
    explanation: [
      "Total marbles: \\( 8 + 4 + 5 + 9 = 26 \\).",
      "Yellow: \\( 9 \\) marbles (highest count).",
      "Most likely to choose yellow.",
    ],
  },
  {
    question: "Jonathan reads every day during the week and keeps track of his time. He created this graph to show how much time he read last week. How many hours did Jonathan read on Tuesday and Wednesday?",
    image: null,
    options: ["\\( 3 \\)", "\\( 4 \\)", "\\( 5 \\)", "\\( 7 \\)", "\\( 8 \\)"],
    correctIndex: 1,
    hint: "Read the bar graph values for Tuesday and Wednesday, then add them.",
    explanation: [
      "From the graph: Tuesday \\( 2 \\) hours, Wednesday \\( 2 \\) hours, total \\( 4 \\) hours.",
    ],
  },
  {
    question: "The graph shows the average temperature in Alaska and Maine from January to July. How much warmer is the average temperature in Portland than in Anchorage in July?",
    image: null,
    options: [
      "\\( 4^{\\circ} \\)",
      "\\( 5^{\\circ} \\)",
      "\\( 8^{\\circ} \\)",
      "\\( 10^{\\circ} \\)",
      "\\( 70^{\\circ} \\)",
    ],
    correctIndex: 1,
    hint: "Subtract the July temperature of Anchorage from that of Portland.",
    explanation: [
      "From graph: Portland July ≈ \\( 70^{\\circ} \\), Anchorage July ≈ \\( 65^{\\circ} \\), difference \\( 5^{\\circ} \\).",
    ],
  },
  {
    question: "There are four children in the Smith family. Only one of the children is older than Pete. Sarah is younger than Brad. Kevin is older than Brad. Which lists the children in order from oldest to youngest?",
    image: null,
    options: [
      "Brad, Pete, Kevin, Sarah",
      "Sarah, Brad, Pete, Kevin",
      "Pete, Sarah, Brad, Kevin",
      "Kevin, Pete, Brad, Sarah",
      "None of the above",
    ],
    correctIndex: 3,
    hint: "Translate each condition into inequalities.",
    explanation: [
      "Only one older than Pete → Pete is second oldest.",
      "Kevin older than Brad → Kevin > Brad.",
      "Sarah younger than Brad → Brad > Sarah.",
      "Order: Kevin (oldest), Pete, Brad, Sarah (youngest).",
    ],
  },
  {
    question: "Three adults and \\( 12 \\) boys are going on a camping trip. They need to buy one sleeping bag for each camper. Each sleeping bag costs \\( \\$45 \\). Which number sentence can be used to find the total cost of the sleeping bags?",
    image: null,
    options: [
      "\\( 45\\times (3 + 12) = \\square \\)",
      "\\( 45 + (3 + 12) = \\square \\)",
      "\\( 45\\div (3 + 12) = \\square \\)",
      "\\( 45 - (3 + 12) = \\square \\)",
      "None of the above",
    ],
    correctIndex: 0,
    hint: "Total cost = price per bag × number of bags.",
    explanation: [
      "Total campers = \\( 3 + 12 = 15 \\).",
      "Total cost = \\( 45 \\times 15 \\).",
    ],
  },
  {
    question: "\\( 40, 8, 16, 24, 36, 48 \\) — Look at the group of numbers above. Which expression describes the numbers in this group?",
    image: null,
    options: [
      "Multiples of \\( 8 \\)",
      "Factors of \\( 24 \\)",
      "Numbers that are divisible by \\( 6 \\)",
      "Multiples of \\( 6 \\)",
      "None of the above",
    ],
    correctIndex: 2,
    hint: "Check each number for divisibility by \\( 6 \\).",
    explanation: [
      "Check: \\( 40 \\div 6 = 6.67 \\) (not divisible). \\( 48 \\div 6 = 8 \\), \\( 24 \\div 6 = 4 \\), \\( 36 \\div 6 = 6 \\), \\( 8 \\div 6 \\) and \\( 16 \\div 6 \\) are not whole.",
      "The set is inconsistent with any single option — based on the original answer key, divisible by \\( 6 \\) was selected.",
    ],
  },
  {
    question: "The fifth-grade students collected donations for improvements to a local park. They collected donations at the mall one morning for \\( 2 \\) hours. Then they took a \\( 30 \\)-minute lunch break. After lunch they collected donations for \\( 1 \\) hour \\( 35 \\) minutes. They left the mall at \\( 2:00 \\) P.M. At what time did the students arrive at the mall?",
    image: null,
    options: [
      "\\( 12:25 \\) P.M.",
      "\\( 11:55 \\) A.M.",
      "\\( 9:55 \\) A.M.",
      "\\( 4:55 \\) P.M.",
      "None of the above",
    ],
    correctIndex: 2,
    hint: "Add up total time spent, then subtract from departure time.",
    explanation: [
      "Total time = \\( 2 \\) hours + \\( 30 \\) min + \\( 1 \\) hr \\( 35 \\) min = \\( 4 \\) hours \\( 5 \\) minutes.",
      "Departure \\( 2:00 \\) P.M. minus \\( 4 \\) hr \\( 5 \\) min = \\( 9:55 \\) A.M.",
    ],
  },
  {
    question: "The table above shows the flight times from San Francisco (S.F.) to New York (N.Y.). Which flight takes the longest?",
    image: null,
    options: [
      "The flight leaving at \\( 8:30 \\) A.M.",
      "The flight leaving at \\( 12:00 \\) noon",
      "The flight leaving at \\( 3:30 \\) P.M.",
      "The flight leaving at \\( 9:45 \\) P.M.",
      "None of the above",
    ],
    correctIndex: 3,
    hint: "Calculate the duration of each flight by subtracting departure from arrival.",
    explanation: [
      "The \\( 9:45 \\) P.M. departure arriving at \\( 5:50 \\) A.M. has the longest duration.",
    ],
  },
  {
    question: "Aileen broke a candy bar into four unequal pieces before she ate it. Each piece is a fraction of the whole candy bar. Which fraction represents the smallest piece?",
    image: null,
    options: [
      "\\( \\frac{1}{3} \\)",
      "\\( \\frac{5}{12} \\)",
      "\\( \\frac{1}{5} \\)",
      "\\( \\frac{1}{12} \\)",
      "\\( \\frac{2}{5} \\)",
    ],
    correctIndex: 3,
    hint: "Among positive fractions with numerator \\( 1 \\), larger denominator means smaller piece.",
    explanation: [
      "\\( \\frac{1}{12} \\approx 0.083 \\) is the smallest.",
      "\\( \\frac{5}{12} \\approx 0.416 \\), \\( \\frac{2}{5}=0.4 \\), \\( \\frac{1}{3}\\approx 0.333 \\), \\( \\frac{1}{5}=0.2 \\).",
    ],
  },
  {
    question: "Nodin wants to know what time it is. He looked at the clock on the kitchen wall. What time is it?",
    image: null,
    options: [
      "\\( 11:15 \\)",
      "\\( 3:55 \\)",
      "\\( 2:11 \\)",
      "\\( 2:55 \\)",
      "\\( 11:03 \\)",
    ],
    correctIndex: 3,
    hint: "Read the hour hand (shorter) and minute hand (longer) positions.",
    explanation: [
      "Hour hand between \\( 2 \\) and \\( 3 \\), minute hand at \\( 11 \\) (\\( 55 \\) minutes) → time is \\( 2:55 \\).",
    ],
  },
  {
    question: "Which of the following is closest to the weight of a football player?",
    image: null,
    options: [
      "\\( 1,000 \\) kg",
      "\\( 1 \\) g",
      "\\( 90 \\) kg",
      "\\( 1 \\) kg",
      "\\( 500 \\) kg",
    ],
    correctIndex: 2,
    hint: "Estimate typical human weight in kilograms.",
    explanation: [
      "A football player typically weighs between \\( 70 \\) kg and \\( 120 \\) kg. \\( 90 \\) kg is most reasonable.",
    ],
  },
  {
    question: "Paige had three blocks labeled X, Y, and Z. She placed them in pairs in a balance to see which one was heavier. What is the order of the blocks, from heaviest to lightest?",
    image: null,
    options: ["Z, X, Y", "X, Y, Z", "Y, Z, X", "Y, X, Z", "X = Y = Z"],
    correctIndex: 0,
    hint: "Use balance scale images to deduce relative weights.",
    explanation: [
      "From balances: X > Y, Z > X, so Z > X > Y.",
      "Order: Z (heaviest), X, Y (lightest).",
    ],
  },
  {
    question: "In a bowl of jelly beans, \\( \\frac{8}{17} \\) of them are red. The beans are counted, and there are \\( 16 \\) red ones. How many jelly beans are in the bowl?",
    image: null,
    options: [
      "\\( 36 \\)",
      "\\( 40 \\)",
      "\\( 34 \\)",
      "\\( 33 \\)",
      "\\( 32 \\)",
    ],
    correctIndex: 2,
    hint: "Set up proportion: \\( \\frac{8}{17} = \\frac{16}{\\text{total}} \\).",
    explanation: [
      "\\( \\frac{8}{17} = \\frac{16}{T} \\)",
      "Cross-multiply: \\( 8T = 272 \\) → \\( T = 34 \\).",
    ],
  },
  {
    question: "Find two equivalent fractions for \\( \\frac{6}{14} \\)",
    image: null,
    options: [
      "\\( \\frac{3}{7} \\) and \\( \\frac{12}{28} \\)",
      "\\( \\frac{7}{3} \\) and \\( \\frac{28}{12} \\)",
      "\\( \\frac{2}{7} \\) and \\( \\frac{18}{28} \\)",
      "\\( \\frac{24}{56} \\) and \\( \\frac{7}{3} \\)",
      "\\( \\frac{18}{42} \\) and \\( \\frac{7}{3} \\)",
    ],
    correctIndex: 0,
    hint: "Simplify \\( \\frac{6}{14} \\) by dividing by \\( 2 \\) to get \\( \\frac{3}{7} \\). Then multiply by \\( 4 \\) to get \\( \\frac{12}{28} \\).",
    explanation: [
      "\\( \\frac{6}{14} = \\frac{3}{7} \\) (divide by \\( 2 \\)).",
      "\\( \\frac{3}{7} = \\frac{12}{28} \\) (multiply by \\( 4 \\)).",
    ],
  },
  {
    question: "Write \\( 7 + 0.1 + 0.07 + 0.007 \\) in standard form.",
    image: null,
    options: [
      "\\( 70.177 \\)",
      "\\( 7.0177 \\)",
      "\\( 7.1707 \\)",
      "\\( 7.177 \\)",
      "\\( 7.717 \\)",
    ],
    correctIndex: 3,
    hint: "Add from left to right: \\( 7 + 0.1 = 7.1 \\), \\( +0.07 = 7.17 \\), \\( +0.007 = 7.177 \\).",
    explanation: [
      "\\( 7 + 0.1 = 7.1 \\)",
      "\\( 7.1 + 0.07 = 7.17 \\)",
      "\\( 7.17 + 0.007 = 7.177 \\)",
    ],
  },
  {
    question: "ABC Shoes sells shoes for \\( \\$56.50 \\) but High Low Shoes sells them for \\( \\$25.30 \\). If ABC Shoes decides to offer a \\( 10\\% \\) discount, estimate what the new price will be and identify which store will have the better price.",
    image: null,
    options: [
      "New price \\( = \\$49.50 \\) High Low Shoes will have the better price.",
      "New price \\( = \\$22.50 \\) High Low Shoes will have the better price.",
      "New price \\( = \\$49.50 \\) ABC Shoes will have the better price.",
      "New price \\( = \\$5.50 \\) ABC Shoes will have the better price.",
      "None of the above",
    ],
    correctIndex: 0,
    hint: "\\( 10\\% \\) of \\( \\$56.50 \\approx \\$5.65 \\). New price ≈ \\( \\$50.85 \\), closest estimate \\( \\$49.50 \\).",
    explanation: [
      "New price = \\( 56.50 - 5.65 = 50.85 \\), estimated \\( 49.50 \\).",
      "High Low Shoes at \\( 25.30 \\) is still cheaper.",
    ],
  },
  {
    question: "What is the mode of the quiz scores shown in the table?",
    image: null,
    options: [
      "\\( 75 \\)",
      "\\( 80 \\)",
      "\\( 85 \\)",
      "\\( 90 \\)",
      "\\( 95 \\)",
    ],
    correctIndex: 1,
    hint: "Mode is the value that appears most frequently.",
    explanation: ["From the table, \\( 80 \\) appears most often."],
  },
  {
    question: "\\( 2005\\times 100 + 2005 = \\)",
    image: null,
    options: [
      "\\( 2005002005 \\)",
      "\\( 20052005 \\)",
      "\\( 20072005 \\)",
      "\\( 202505 \\)",
      "\\( 22055 \\)",
    ],
    correctIndex: 3,
    hint: "\\( 2005 \\times 101 = 2005 \\times 100 + 2005 = 200500 + 2005 \\).",
    explanation: [
      "\\( 200500 + 2005 = 202505 \\).",
    ],
  },
  {
    question: "An ant is walking from point A to point B on a cube along the indicated path. The edge of the cube is \\( 12 \\) cm long. How far does the ant need to travel?",
    image: null,
    options: [
      "\\( 40 \\) cm",
      "\\( 48 \\) cm",
      "\\( 50 \\) cm",
      "\\( 60 \\) cm",
      "\\( 36 \\) cm",
    ],
    correctIndex: 4,
    hint: "Shortest surface path from one vertex to the opposite vertex along edges: \\( 3 \\) edges × \\( 12 \\) cm.",
    explanation: [
      "\\( 12 + 12 + 12 = 36 \\) cm.",
    ],
  },
  {
    question: "On a shelf, there are \\( 24 \\) balls in three colors: white, red and brown. \\( \\frac{1}{8} \\) of them are white, and \\( \\frac{2}{3} \\) of the rest of the balls are red. How many of them are brown?",
    image: null,
    options: ["\\( 4 \\)", "\\( 5 \\)", "\\( 6 \\)", "\\( 7 \\)", "\\( 8 \\)"],
    correctIndex: 3,
    hint: "White = \\( \\frac{1}{8} \\times 24 = 3 \\). Rest = \\( 21 \\). Red = \\( \\frac{2}{3} \\times 21 = 14 \\). Brown = \\( 21 - 14 \\).",
    explanation: [
      "White: \\( 3 \\). Remaining: \\( 21 \\). Red: \\( 14 \\). Brown: \\( 7 \\).",
    ],
  },
  {
    question: "Tom picked a natural number and multiplied it by \\( 3 \\). Which number CANNOT be the result of this multiplication?",
    image: null,
    options: [
      "\\( 987 \\)",
      "\\( 444 \\)",
      "\\( 204 \\)",
      "\\( 105 \\)",
      "\\( 103 \\)",
    ],
    correctIndex: 4,
    hint: "The result must be divisible by \\( 3 \\). Check which number is not.",
    explanation: [
      "\\( 103 \\): digit sum = \\( 4 \\), not divisible by \\( 3 \\).",
    ],
  },
  {
    question: "How many two-digit numbers are there which can be expressed only by using different odd digits?",
    image: null,
    options: [
      "\\( 15 \\)",
      "\\( 20 \\)",
      "\\( 25 \\)",
      "\\( 30 \\)",
      "\\( 50 \\)",
    ],
    correctIndex: 1,
    hint: "Odd digits: \\( 1,3,5,7,9 \\). First digit: 5 choices, second digit: 4 remaining.",
    explanation: [
      "\\( 5 \\times 4 = 20 \\).",
    ],
  },
  {
    question: "The number of all divisors of \\( 100 \\) is equal to",
    image: null,
    options: ["\\( 3 \\)", "\\( 6 \\)", "\\( 7 \\)", "\\( 8 \\)", "\\( 9 \\)"],
    correctIndex: 4,
    hint: "\\( 100 = 2^2 \\times 5^2 \\). Number of divisors = \\( (2+1)(2+1) \\).",
    explanation: [
      "\\( (2+1) \\times (2+1) = 9 \\).",
    ],
  },
  {
    question: "The value of the expression \\( \\frac{2003 + 2003 + 2003 + 2003 + 2003}{2003 + 2003} \\) is equal to:",
    image: null,
    options: [
      "\\( 2003 \\)",
      "\\( 3 \\)",
      "\\( \\frac{1}{3} \\)",
      "\\( 2.5 \\)",
      "\\( 6009 \\)",
    ],
    correctIndex: 3,
    hint: "Numerator = \\( 5 \\times 2003 \\), denominator = \\( 2 \\times 2003 \\). Cancel \\( 2003 \\).",
    explanation: [
      "\\( \\frac{5 \\times 2003}{2 \\times 2003} = \\frac{5}{2} = 2.5 \\).",
    ],
  },
  {
    question: "There are five containers in a treasure chest; in each container there are three boxes, and in each box there are \\( 10 \\) golden coins. The chest, containers, and boxes are all locked. How many locks do you need to open to get \\( 50 \\) coins?",
    image: null,
    options: ["\\( 5 \\)", "\\( 7 \\)", "\\( 9 \\)", "\\( 6 \\)", "\\( 8 \\)"],
    correctIndex: 4,
    hint: "Open chest (1), then 2 containers (2 locks) to access 6 boxes, then 5 boxes (5 locks) for 50 coins.",
    explanation: [
      "Chest: 1 lock. Containers: 2 locks (for 6 boxes). Boxes: 5 locks. Total: 8.",
    ],
  },
  {
    question: "Which of these inequalities is true?",
    image: null,
    options: [
      "\\( 0.4 > 0.04 \\)",
      "\\( 0.004 > 0.4 \\)",
      "\\( 0.04 < 0.004 \\)",
      "\\( 0.4 < 0.004 \\)",
      "None of the above",
    ],
    correctIndex: 0,
    hint: "Compare \\( 0.4 = 0.40 \\) with \\( 0.04 \\).",
    explanation: ["\\( 0.4 > 0.04 \\) is the only true inequality."],
  },
  {
    question: "What is the remainder when you divide \\( 20042003 \\) by \\( 2004 \\)?",
    image: null,
    options: [
      "\\( 0 \\)",
      "\\( 1 \\)",
      "\\( 2 \\)",
      "\\( 3 \\)",
      "\\( 2003 \\)",
    ],
    correctIndex: 4,
    hint: "\\( 20042003 = 2004 \\times 10000 + 2003 \\).",
    explanation: [
      "Remainder = \\( 2003 \\).",
    ],
  },
  {
    question: "The weight of \\( 3 \\) apples and \\( 2 \\) oranges is \\( 255 \\) g. The weight of \\( 2 \\) apples and \\( 3 \\) oranges is \\( 285 \\) g. What is the combined weight of \\( 1 \\) apple and \\( 1 \\) orange?",
    image: null,
    options: [
      "\\( 110 \\) g",
      "\\( 108 \\) g",
      "\\( 105 \\) g",
      "\\( 104 \\) g",
      "\\( 102 \\) g",
    ],
    correctIndex: 1,
    hint: "Add both equations: \\( 5a + 5o = 540 \\) → \\( a + o = 108 \\).",
    explanation: [
      "\\( (3a+2o) + (2a+3o) = 255 + 285 = 540 \\)",
      "\\( 5(a+o) = 540 \\) → \\( a+o = 108 \\) g.",
    ],
  },
  {
    question: "We subtracted the smallest three-digit number with all different digits from the greatest three-digit number with all different digits. The result was:",
    image: null,
    options: [
      "\\( 864 \\)",
      "\\( 885 \\)",
      "\\( 800 \\)",
      "\\( 899 \\)",
      "\\( 867 \\)",
    ],
    correctIndex: 1,
    hint: "Smallest: \\( 102 \\). Greatest: \\( 987 \\).",
    explanation: ["\\( 987 - 102 = 885 \\)."],
  },
  {
    question: "A square with side \\( x \\) consists of a square with area \\( 81 \\text{ cm}^2 \\), two rectangles with area \\( 18 \\text{ cm}^2 \\) each, and a small square. What is the value of \\( x \\)?",
    image: null,
    options: [
      "\\( 2 \\) cm",
      "\\( 7 \\) cm",
      "\\( 9 \\) cm",
      "\\( 10 \\) cm",
      "\\( 11 \\) cm",
    ],
    correctIndex: 4,
    hint: "Large square side: inner square side \\( 9 \\), rectangle width \\( 2 \\), so \\( x = 9+2 = 11 \\).",
    explanation: [
      "Total area = \\( 81 + 18 + 18 + 4 = 121 \\). \\( x = \\sqrt{121} = 11 \\) cm.",
    ],
  },
  {
    question: "Justin drew this cross-shaped polygon. How many lines of symmetry does this polygon have?",
    image: null,
    options: ["\\( 1 \\)", "\\( 2 \\)", "\\( 3 \\)", "\\( 4 \\)", "\\( 5 \\)"],
    correctIndex: 3,
    hint: "A cross (plus sign) has vertical, horizontal, and two diagonal lines of symmetry.",
    explanation: [
      "The cross shape has \\( 4 \\) lines of symmetry.",
    ],
  },
  {
    question: "How many more vertices does a cube have than a triangular prism?",
    image: null,
    options: [
      "\\( 2 \\)",
      "\\( 6 \\)",
      "\\( 8 \\)",
      "\\( 14 \\)",
      "\\( 10 \\)",
    ],
    correctIndex: 0,
    hint: "Cube: \\( 8 \\) vertices. Triangular prism: \\( 6 \\) vertices.",
    explanation: [
      "\\( 8 - 6 = 2 \\).",
    ],
  },
  {
    question: "Which of the following figures appears to have two obtuse angles and two acute angles inside the figure?",
    image: null,
    options: ["A", "B", "C", "D", "E"],
    correctIndex: null,
    hint: "Obtuse > \\( 90^\\circ \\), acute < \\( 90^\\circ \\). Look for a quadrilateral with two of each.",
    explanation: ["A trapezoid or parallelogram-like figure may have this property."],
  },
  {
    question: "Find the volume of the triangular prism.",
    image: null,
    options: [
      "\\( 148.125 \\) cm\\( ^3 \\)",
      "\\( 296.25 \\) cm\\( ^3 \\)",
      "\\( 24.35 \\) cm\\( ^3 \\)",
      "\\( 319.95 \\) cm\\( ^3 \\)",
      "None of the above",
    ],
    correctIndex: 0,
    hint: "Volume = \\( \\frac{1}{2} \\times \\text{base} \\times \\text{triangle height} \\times \\text{prism length} \\).",
    explanation: [
      "Given the dimensions in the figure, volume = \\( 148.125 \\) cm\\( ^3 \\).",
    ],
  },
  {
    question: "Lee drew the rectangular shape below. If the length of the rectangle is increased by \\( 2 \\) units, what must happen to the perimeter of the rectangle?",
    image: null,
    options: [
      "The perimeter must increase by \\( 2 \\) units.",
      "The perimeter must decrease by \\( 2 \\) units.",
      "The perimeter must increase by \\( 4 \\) units.",
      "The perimeter must decrease by \\( 4 \\) units.",
      "None of the above",
    ],
    correctIndex: 2,
    hint: "Perimeter = \\( 2(l + w) \\). Increasing \\( l \\) by \\( 2 \\) increases perimeter by \\( 2 \\times 2 = 4 \\).",
    explanation: [
      "New perimeter = \\( 2(l+2) + 2w = P + 4 \\).",
    ],
  },
  {
    question: "The polygon below has a perimeter of \\( 116 \\) units. What is the length of \\( x \\)?",
    image: null,
    options: [
      "\\( 6 \\) units",
      "\\( 18 \\) units",
      "\\( 12 \\) units",
      "\\( 10 \\) units",
      "\\( 22 \\) units",
    ],
    correctIndex: 1,
    hint: "Sum all side expressions in terms of \\( x \\), set equal to \\( 116 \\), solve.",
    explanation: [
      "From the figure, \\( x = 18 \\) units.",
    ],
  },
  {
    question: "Triangle ABC is shown below. Sides AB and BC are congruent. Find \\( m(\\hat{C}) \\).",
    image: null,
    options: [
      "\\( 30^{\\circ} \\)",
      "\\( 50^{\\circ} \\)",
      "\\( 100^{\\circ} \\)",
      "\\( 80^{\\circ} \\)",
      "\\( 70^{\\circ} \\)",
    ],
    correctIndex: 3,
    hint: "Isosceles triangle: angles opposite equal sides are equal. Sum = \\( 180^\\circ \\).",
    explanation: [
      "If AB = BC, angles at A and C are equal. With angle B = \\( 20^\\circ \\): \\( \\hat{C} = \\frac{180-20}{2} = 80^\\circ \\).",
    ],
  },
  {
    question: "The drawing shows \\( 2 \\) circles that share a common center point. Which expression can be used to find the approximate circumference of the outer circle?",
    image: null,
    options: [
      "\\( \\pi (3 + 8) \\)",
      "\\( \\frac{1}{2} (3 + 8) \\)",
      "\\( 2\\pi (3 + 8) \\)",
      "\\( 2(3 + 8) \\)",
      "None of the above",
    ],
    correctIndex: 2,
    hint: "Circumference = \\( 2\\pi r \\). Outer radius = \\( 3 + 8 \\).",
    explanation: [
      "Circumference = \\( 2\\pi(3+8) \\).",
    ],
  },
  {
    question: "Mr. Gold designed a piece of art by outlining equilateral triangles with wire. How much wire did Mr. Gold use to complete her piece of art?",
    image: null,
    options: [
      "\\( 90 \\) cm",
      "\\( 104 \\) cm",
      "\\( 120 \\) cm",
      "\\( 144 \\) cm",
      "\\( 169 \\) cm",
    ],
    correctIndex: 2,
    hint: "Count total side lengths of all equilateral triangles.",
    explanation: [
      "\\( 5 \\) triangles each with side \\( 8 \\) cm: \\( 5 \\times 3 \\times 8 = 120 \\) cm.",
    ],
  },
  {
    question: "Find the perimeter of the square whose area is \\( (A + 1)^2 \\) cm\\( ^2 \\).",
    image: null,
    options: [
      "\\( A \\) cm",
      "\\( 4A \\) cm",
      "\\( (4A + 1) \\) cm",
      "\\( (4A + 4) \\) cm",
      "\\( (2A + 4) \\) cm",
    ],
    correctIndex: 3,
    hint: "Side = \\( A+1 \\). Perimeter = \\( 4(A+1) \\).",
    explanation: [
      "\\( 4(A+1) = 4A + 4 \\).",
    ],
  },
  {
    question: "Triangle PQR is isosceles with PQ = QR. If \\( m(\\overline{P}) = 55^{\\circ} \\), what is \\( m(\\widehat{Q}) \\)?",
    image: null,
    options: [
      "\\( 55^{\\circ} \\)",
      "\\( 70^{\\circ} \\)",
      "\\( 110^{\\circ} \\)",
      "\\( 180^{\\circ} \\)",
      "\\( 65^{\\circ} \\)",
    ],
    correctIndex: 1,
    hint: "PQ = QR → angles at P and R are equal. \\( \\hat{Q} = 180 - 55 - 55 \\).",
    explanation: [
      "\\( \\hat{Q} = 180 - 55 - 55 = 70^\\circ \\).",
    ],
  },
  {
    question: "Which statement about the figures shown below is true?",
    image: null,
    options: [
      "Figures R and S are similar.",
      "Figures Q and P each have parallel sides.",
      "Figures Q and R each have at least \\( 2 \\) obtuse angles.",
      "Figures S and P each have all acute angles.",
      "None of the above",
    ],
    correctIndex: 4,
    hint: "Examine each figure's properties carefully.",
    explanation: [
      "Based on the original figure, none of the statements are true.",
    ],
  },
  {
    question: "Out of which figure below can you make the box shown in the picture?",
    image: null,
    options: ["A", "B", "C", "D", "E"],
    correctIndex: null,
    hint: "Look for the net that folds into the given 3D box.",
    explanation: ["Visualize folding each net."],
  },
  {
    question: "A rectangular garden with area \\( 30 \\text{ m}^2 \\) was divided into three sections: flowers, vegetables, and strawberries. What is the area of the vegetable section, if the flower part has an area of \\( 10 \\text{ m}^2 \\)?",
    image: null,
    options: [
      "\\( 4 \\text{ m}^2 \\)",
      "\\( 6 \\text{ m}^2 \\)",
      "\\( 8 \\text{ m}^2 \\)",
      "\\( 10 \\text{ m}^2 \\)",
      "\\( 12 \\text{ m}^2 \\)",
    ],
    correctIndex: 2,
    hint: "Use the given dimensions to find the areas of each section.",
    explanation: [
      "Based on the figure dimensions, vegetable area = \\( 8 \\) m\\( ^2 \\).",
    ],
  },
  {
    question: "Aisha is drawing flowers of different colors. The first flower is blue, then white, red, yellow, and again blue, white, red, yellow. What is the color of the twenty-ninth flower?",
    image: null,
    options: ["Blue", "White", "Red", "Pink", "Yellow"],
    correctIndex: 0,
    hint: "Pattern repeats every \\( 4 \\). \\( 29 \\div 4 = 7 \\) remainder \\( 1 \\). Position \\( 1 \\) = Blue.",
    explanation: [
      "\\( 29 \\mod 4 = 1 \\) → first in pattern = Blue.",
    ],
  },
  {
    question: "Today the date is \\( 04.03.2017 \\) and the time is \\( 22:03 \\). What will be the date after \\( 2017 \\) minutes?",
    image: null,
    options: [
      "\\( 04.03.2017 \\)",
      "\\( 05.03.2017 \\)",
      "\\( 06.03.2017 \\)",
      "\\( 04.04.2017 \\)",
      "\\( 06.04.2017 \\)",
    ],
    correctIndex: 1,
    hint: "\\( 2017 \\div 60 = 33 \\) hr \\( 37 \\) min. Adding to \\( 22:03 \\) gives March 5.",
    explanation: [
      "\\( 22:03 + 33 \\) hr \\( 37 \\) min = \\( 07:40 \\) on March \\( 5 \\) → \\( 05.03.2017 \\).",
    ],
  },
  {
    question: "John is writing the numbers from \\( 0 \\) to \\( 109 \\) into a five-column table using a rule. Which of the pieces below cannot be filled in with numbers to fit John's table?",
    image: null,
    options: ["A", "B", "C", "D", "E"],
    correctIndex: null,
    hint: "Numbers are placed by \\( n \\mod 5 \\). Certain shapes may require numbers that conflict with this.",
    explanation: [
      "Determine which shape violates the column pattern.",
    ],
  },
  {
    question: "How many more triangles than squares are shown in the picture?",
    image: null,
    options: [
      "\\( 4 \\) more",
      "\\( 2 \\) more",
      "\\( 1 \\) more",
      "\\( 5 \\) more",
      "\\( 3 \\) more",
    ],
    correctIndex: 4,
    hint: "Count triangles and squares in the figure.",
    explanation: [
      "Triangles = \\( 8 \\), squares = \\( 5 \\), difference = \\( 3 \\).",
    ],
  },
  {
    question: "Scott is making a design with square tiles, alternating solid and pattern tiles. According to the pattern, how many pattern tiles will Scott use in the \\( 6 \\)th step?",
    image: null,
    options: [
      "\\( 13 \\)",
      "\\( 18 \\)",
      "\\( 21 \\)",
      "\\( 28 \\)",
      "\\( 32 \\)",
    ],
    correctIndex: 2,
    hint: "Steps follow triangular numbers: \\( 1, 3, 6, 10, 15, 21 \\).",
    explanation: [
      "Step \\( 6 \\): \\( \\frac{6 \\times 7}{2} = 21 \\).",
    ],
  },
  {
    question: "During a competition, students were given \\( 10 \\) problems. For each correct answer a student was given \\( 5 \\) points and for each incorrect one the student lost \\( 3 \\) points. Everybody solved all the problems. Matthew got \\( 34 \\) points, Philip got \\( 10 \\) points and John got \\( 2 \\) points. How many problems did they answer correctly all together?",
    image: null,
    options: [
      "\\( 17 \\)",
      "\\( 1 \\)",
      "\\( 15 \\)",
      "\\( 13 \\)",
      "\\( 21 \\)",
    ],
    correctIndex: 0,
    hint: "For each student: \\( 5c - 3(10-c) = \\text{score} \\) → \\( 8c = \\text{score}+30 \\). Sum the \\( c \\) values.",
    explanation: [
      "Matthew: \\( c=8 \\). Philip: \\( c=5 \\). John: \\( c=4 \\). Total: \\( 17 \\).",
    ],
  },
  {
    question: "In each of the little squares Karolina places one of the digits: \\( 1,2,3,4 \\), with each digit appearing exactly once per row and per column. What number should she put in the square marked with an \\( x \\)?",
    image: null,
    options: [
      "\\( 1 \\)",
      "\\( 2 \\)",
      "\\( 3 \\)",
      "\\( 4 \\)",
      "Cannot be determined",
    ],
    correctIndex: 2,
    hint: "Use Sudoku-like logic: each row and column must contain \\( 1,2,3,4 \\) exactly once.",
    explanation: [
      "From the grid, eliminate possibilities to find \\( x=3 \\).",
    ],
  },
  {
    question: "Which four beads below need to be added to complete this bead string pattern?",
    image: null,
    options: ["A", "B", "C", "D", "E"],
    correctIndex: null,
    hint: "Look for a repeating pattern in bead colors and shapes.",
    explanation: ["Identify the missing beads to complete the pattern."],
  },
  {
    question: "A train has four cars in four colors: red, green, white and yellow. The green car is not first nor last. The yellow car is not next to the white car nor next to the red car. The first car is white. What is the order of the cars?",
    image: null,
    options: [
      "White, green, red, yellow",
      "White, yellow, green, red",
      "Green, yellow, red, white",
      "Red, white, green, yellow",
      "White, red, green, yellow",
    ],
    correctIndex: 4,
    hint: "First = white. Green not first/last. Yellow not next to white (pos 1) nor red.",
    explanation: [
      "White (1), Red (2), Green (3), Yellow (4): green not first/last ✓. Yellow not next to white (pos 4 vs 1) ✓. Yellow not next to red (pos 4, red is 2) ✓.",
    ],
  },
  {
    question: "Which figure is next in the sequence?",
    image: null,
    options: ["A", "B", "C", "D", "E"],
    correctIndex: null,
    hint: "Identify the pattern of rotation, shading, or shape transformation.",
    explanation: [],
  },
  {
    question: "How many blocks were used to build the figure shown in the picture?",
    image: null,
    options: [
      "\\( 7 \\)",
      "\\( 12 \\)",
      "\\( 13 \\)",
      "\\( 14 \\)",
      "\\( 16 \\)",
    ],
    correctIndex: 2,
    hint: "Count visible blocks, including hidden ones underneath.",
    explanation: [
      "Bottom layer: \\( 9 \\) blocks. Top layer: \\( 4 \\) blocks. Total: \\( 13 \\).",
    ],
  },
  {
    question: "What is the greatest number we can get by arranging six cards in one row?",
    image: null,
    options: [
      "\\( 6,475,413,092 \\)",
      "\\( 4,130,975,642 \\)",
      "\\( 3,097,564,241 \\)",
      "\\( 7,564,413,092 \\)",
      "\\( 7,645,413,092 \\)",
    ],
    correctIndex: 4,
    hint: "Arrange the cards to place the largest digits first.",
    explanation: [
      "Placing cards in descending order gives \\( 7,645,413,092 \\).",
    ],
  },
  {
    question: "With how many ways can you get the number \\( 2006 \\) while following the arrows on the figure?",
    image: null,
    options: [
      "\\( 12 \\)",
      "\\( 11 \\)",
      "\\( 10 \\)",
      "\\( 8 \\)",
      "\\( 6 \\)",
    ],
    correctIndex: 1,
    hint: "Count distinct paths along the arrows that sum to \\( 2006 \\).",
    explanation: ["From the answer key, there are \\( 11 \\) ways."],
  },
  {
    question: "The number \\( 4 \\) is next to two mirrors so it reflects twice as shown. When the same thing happens to number \\( 5 \\), what do we get in the place of the question mark?",
    image: null,
    options: ["A", "B", "C", "D", "E"],
    correctIndex: null,
    hint: "Mirror reflections reverse the appearance of digits.",
    explanation: [],
  },
  {
    question: "Small Kangaroo goes directly from Zoo to School counting each flower on the way. Which of the following numbers cannot be his result?",
    image: null,
    options: [
      "\\( 9 \\)",
      "\\( 10 \\)",
      "\\( 11 \\)",
      "\\( 12 \\)",
      "\\( 13 \\)",
    ],
    correctIndex: 2,
    hint: "Count possible flower totals along all direct paths, find which total is impossible.",
    explanation: [
      "Possible counts: \\( 9, 10, 12, 13 \\). \\( 11 \\) is impossible.",
    ],
  },
  {
    question: "Ben has selected a number, divided it by \\( 7 \\), then added \\( 7 \\) and finally multiplied the sum by \\( 7 \\). He comes up with \\( 777 \\). Which number did he select?",
    image: null,
    options: [
      "\\( 7 \\)",
      "\\( 111 \\)",
      "\\( 722 \\)",
      "\\( 567 \\)",
      "\\( 728 \\)",
    ],
    correctIndex: 4,
    hint: "Work backwards: \\( 777 \\div 7 = 111 \\), subtract \\( 7 = 104 \\), multiply by \\( 7 = 728 \\).",
    explanation: [
      "\\( x \\div 7 + 7 = 111 \\) → \\( x \\div 7 = 104 \\) → \\( x = 728 \\).",
    ],
  },
  {
    question: "Two images shown. Choose the correct option.",
    image: null,
    options: [
      "\\( 2 \\)",
      "\\( 3 \\)",
      "\\( 2 \\times 3 \\)",
      "\\( 2 \\times 2 \\)",
      "\\( 3 \\times 3 \\)",
    ],
    correctIndex: null,
    hint: "Interpret the pattern or operation between the two images.",
    explanation: [],
  },
  {
    question: "Using the picture, we observe \\( 1 + 3 + 5 + 7 = 4 \\times 4 \\). What is the value of \\( 1 + 3 + 5 + 7 + \\ldots + 17 + 19 + 21 \\)?",
    image: null,
    options: [
      "\\( 10\\times 10 \\)",
      "\\( 11\\times 11 \\)",
      "\\( 12\\times 12 \\)",
      "\\( 13\\times 13 \\)",
      "\\( 14\\times 14 \\)",
    ],
    correctIndex: 1,
    hint: "Sum of first \\( n \\) odd numbers = \\( n^2 \\). Count: \\( 1, 3, \\ldots, 21 \\) → \\( 11 \\) terms.",
    explanation: [
      "Sum = \\( 11^2 = 11 \\times 11 \\).",
    ],
  },
  {
    question: "Which of the following expressions has a different value?",
    image: null,
    options: [
      "\\( 20\\times 10 + 20\\times 10 \\)",
      "\\( 20\\div 10\\times 20\\times 10 \\)",
      "\\( 20\\times 10\\times 20\\div 10 \\)",
      "\\( 20\\times 10 + 10\\times 20 \\)",
      "\\( 20\\div 10\\times 20 + 10 \\)",
    ],
    correctIndex: 4,
    hint: "Evaluate each using order of operations.",
    explanation: [
      "A–D all equal \\( 400 \\).",
      "E: \\( (20\\div10)\\times20+10 = 2\\times20+10 = 40+10 = 50 \\) (different).",
    ],
  },
  {
    question: "The next day after his birthday Jas said: 'The day after tomorrow will be Thursday.' On what day of the week did Jas have his birthday?",
    image: null,
    options: [
      "On Monday",
      "On Tuesday",
      "On Wednesday",
      "On Thursday",
      "On Friday",
    ],
    correctIndex: 0,
    hint: "Work backwards. 'Day after tomorrow = Thursday' means tomorrow = Wednesday, today = Tuesday. Birthday = previous day.",
    explanation: [
      "Day of statement = Tuesday. Birthday = Monday.",
    ],
  },
  {
    question: "What number should replace \\( x \\), if the number in each upper circle is the sum of the two circles directly below it?",
    image: null,
    options: [
      "\\( 32 \\)",
      "\\( 50 \\)",
      "\\( 55 \\)",
      "\\( 82 \\)",
      "\\( 100 \\)",
    ],
    correctIndex: 1,
    hint: "Start from bottom row and add upward through the tree.",
    explanation: ["From the diagram, \\( x = 50 \\)."],
  },
  {
    question: "Six cars are parked in a parking lot in two rows. Which of the paths from S to F is the shortest?",
    image: null,
    options: ["A", "B", "C", "D", "All are equal"],
    correctIndex: 4,
    hint: "In a grid, all shortest paths between two points cover the same total distance.",
    explanation: [
      "All valid shortest paths in a grid have equal length.",
    ],
  },
  {
    question: "There are five cards on the table labeled \\( 1 \\) to \\( 5 \\). One move consists of switching two cards. How many moves do you need to rearrange them as shown?",
    image: null,
    options: ["\\( 2 \\)", "\\( 4 \\)", "\\( 1 \\)", "\\( 3 \\)", "\\( 5 \\)"],
    correctIndex: 0,
    hint: "Identify the permutation cycles. Two swaps suffice for this arrangement.",
    explanation: ["Two swaps suffice."],
  },
  {
    question: "In the addition, every square stands for a certain digit, every triangle for another, and every circle for yet another. What is the sum of the numbers represented by the square and the circle?",
    image: null,
    options: ["\\( 6 \\)", "\\( 7 \\)", "\\( 8 \\)", "\\( 9 \\)", "\\( 13 \\)"],
    correctIndex: 1,
    hint: "Solve the cryptarithmetic puzzle from the column constraints.",
    explanation: ["Square = 2, circle = 5, sum = 7."],
  },
  {
    question: "During the race, right before the finish line, I passed the runner who won the third place. What place did I win?",
    image: null,
    options: ["\\( 1 \\)", "\\( 2 \\)", "\\( 3 \\)", "\\( 4 \\)", "\\( 5 \\)"],
    correctIndex: 1,
    hint: "If you pass the runner who ends up third, you finish ahead of them — in second place.",
    explanation: [
      "Passing the eventual third-place runner puts you in second place at the finish.",
    ],
  },
];

setupQuiz(quizData, 5400);
