/**
 * cbt-bank.js — local-first reader for the CBT practice bank.
 *
 * Practice is served from the static export in /data/cbt/ (generated by
 * server/scripts/export-cbt-bank.js), so a student session costs ≈0 Firestore
 * reads. If a static file is missing (e.g. local dev before an export, or a bad
 * deploy) we fall back to the live /api/cbt endpoints.
 *
 *   manifest()                                   → navigation index (classes + exams)
 *   paperQuestions(axis, topKey, subject, topic, paper) → that paper's ≤60 questions
 *
 * axis: "class" → files in /data/cbt/c/<class>__<subject>.js
 *       "exam"  → files in /data/cbt/e/<scheme>__<subject>.js
 */

const API_BASE = window.location.port === "5500" ? "http://127.0.0.1:5000" : "";
const PAPER_SIZE = 60;

let _manifest;
let _manifestTried = false;
const _buckets = new Map();

/** The navigation index (classes[] + exams.national[]/international[]). */
export async function manifest() {
  if (_manifestTried) return _manifest;
  _manifestTried = true;
  try {
    _manifest = (await import("/data/cbt/manifest.js")).MANIFEST || null;
  } catch (e) {
    _manifest = null; // caller falls back to live endpoints
  }
  return _manifest;
}

/** All questions for a class/exam + subject bucket (cached; [] if absent). */
async function bucket(axis, topKey, subject) {
  const dir = axis === "exam" ? "e" : "c";
  const file = `/data/cbt/${dir}/${encodeURIComponent(topKey)}__${encodeURIComponent(subject)}.js`;
  if (_buckets.has(file)) return _buckets.get(file);
  let qs = [];
  try {
    qs = (await import(file)).QUESTIONS || [];
  } catch (e) {
    qs = [];
  }
  _buckets.set(file, qs);
  return qs;
}

/**
 * The questions for one paper (≤60). Local file first; on miss, fall back to the
 * live API (class mode → /api/cbt?class=…; exam mode → /api/cbt?scheme=…).
 */
export async function paperQuestions(axis, topKey, subject, topic, paper, paperSize = PAPER_SIZE) {
  const all = await bucket(axis, topKey, subject);
  if (all.length) {
    const inTopic = all.filter((q) => (q.topic || "General") === topic);
    const start = (Math.max(1, parseInt(paper, 10) || 1) - 1) * paperSize;
    return inTopic.slice(start, start + paperSize);
  }
  // Fallback: live endpoint.
  try {
    const p = new URLSearchParams({ subject, topic, paper: String(paper || 1), limit: String(paperSize) });
    if (axis === "exam") p.set("scheme", topKey); else p.set("class", topKey);
    const r = await fetch(`${API_BASE}/api/cbt?${p}`);
    if (!r.ok) return [];
    return (await r.json()).questions || [];
  } catch (e) {
    return [];
  }
}
