/**
 * cbt-static.js — the LOCAL static-bank store.
 *
 * The committed files under data/cbt/ are the SOURCE OF TRUTH for the CBT bank:
 *   data/cbt/c/<class>__<subject>.js   class buckets   (export const QUESTIONS=[…])
 *   data/cbt/e/<scheme>__<subject>.js  exam  buckets
 *   data/cbt/manifest.js               navigation index (derived from the buckets)
 *   data/cbt/_topics.json              curated topic registry (incl. empty topics)
 *
 * Editing happens HERE, on disk, with ZERO Firestore reads/writes — the admin
 * commits the result locally and Vercel serves it. Firestore is a write-only
 * backup, pushed on demand by scripts/sync-cbt-firestore.js. This module owns
 * every read/mutate of the static files; it mirrors the slim shape + placement
 * rules of scripts/export-cbt-bank.js so files stay byte-compatible (clean diffs).
 */

const fs = require("fs");
const path = require("path");

const OUT_DIR = path.join(__dirname, "..", "..", "data", "cbt");
const PAPER_SIZE = 60;
const HEADER = "// AUTO-GENERATED by server/scripts/export-cbt-bank.js — do not edit by hand.";

// ── Labels / placement (mirror export-cbt-bank.js + routes/cbt.js) ──────────
const CLASS_LABELS = {};
for (let i = 1; i <= 12; i++) CLASS_LABELS["grade" + i] = "Grade " + i;
const CLASS_ORDER = Object.keys(CLASS_LABELS);
const LEGACY_CLASS = {
  primary1: "grade1", primary2: "grade2", primary3: "grade3", primary4: "grade4", primary5: "grade5", primary6: "grade6",
  jss1: "grade7", jss2: "grade8", jss3: "grade9", sss1: "grade10", sss2: "grade11", sss3: "grade12",
};
const normClass = (cl) => LEGACY_CLASS[cl] || cl;
const SUBJECT_LABELS = {
  english: "English Language", mathematics: "Mathematics", biology: "Biology",
  physics: "Physics", chemistry: "Chemistry", economics: "Economics",
  government: "Government", commerce: "Commerce", geography: "Geography",
  crk: "Christian Religious Studies", irk: "Islamic Religious Studies",
  englishlit: "Literature in English", accounting: "Financial Accounting",
  history: "History", civiledu: "Civic Education", agric: "Agricultural Science",
  quantitative: "Quantitative Reasoning", verbal: "Verbal Reasoning",
  generalstudies: "General Studies", furthermaths: "Further Mathematics",
  ict: "ICT", businessstudies: "Business Studies",
};
const EXAMS = {
  national: { utme: "UTME-style", wassce: "WASSCE-style", postutme: "Post-UTME style", cee: "Common Entrance style" },
  international: { sat: "SAT-style", igcse: "IGCSE-style", alevel: "A-Level-style" },
};
const EXAM_OF = {};
for (const region of Object.keys(EXAMS)) for (const k of Object.keys(EXAMS[region])) EXAM_OF[k] = region;

const subjLabel = (k) => SUBJECT_LABELS[k] || (k ? k[0].toUpperCase() + k.slice(1) : "Subject");
const topicKeyOf = (t) =>
  String(t == null ? "" : t).toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "general";
const csKey = (cl, subj) => `${cl}__${subj}`;

// Slim a record to exactly the served fields, in the SAME key order as the
// export, so re-writing an unchanged bucket yields an identical file.
function slim(id, x) {
  return {
    id, type: x.type || "objective", question: x.question,
    options: x.options || null, answerIndex: typeof x.answerIndex === "number" ? x.answerIndex : null,
    answer: x.answer || null, explanation: x.explanation || "", hint: x.hint || "",
    image: x.image || null, video: x.video || null, videoScope: x.videoScope || "question",
    topic: x.topic || "General", classLevel: x.classLevel || null,
    scheme: x.scheme || null, subject: x.subject, subjectLabel: x.subjectLabel || subjLabel(x.subject), grade: x.grade || null,
  };
}

// A 20-char id in the Firestore auto-id alphabet (so the backup keeps the shape).
const ID_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
function newId() {
  let s = "";
  for (let i = 0; i < 20; i++) s += ID_ALPHABET[Math.floor(Math.random() * ID_ALPHABET.length)];
  return s;
}

// ── Bucket file IO ──────────────────────────────────────────────────────────
const bucketDir = (axis) => path.join(OUT_DIR, axis === "exam" ? "e" : "c");
const bucketFile = (axis, key) => path.join(bucketDir(axis), key + ".js");

function readBucket(axis, key) {
  try {
    const txt = fs.readFileSync(bucketFile(axis, key), "utf8");
    const m = txt.match(/export const QUESTIONS\s*=\s*(\[[\s\S]*\]);/);
    return m ? JSON.parse(m[1]) : [];
  } catch (_) {
    return [];
  }
}
function writeBucket(axis, key, arr) {
  const file = bucketFile(axis, key);
  if (!arr.length) { try { fs.rmSync(file, { force: true }); } catch (_) {} return; }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${HEADER}\nexport const QUESTIONS = ${JSON.stringify(arr)};\n`);
}
function listKeys(axis) {
  try { return fs.readdirSync(bucketDir(axis)).filter((f) => f.endsWith(".js")).map((f) => f.slice(0, -3)); }
  catch (_) { return []; }
}

// Which bucket(s) a record belongs in (a question can live in a class bucket
// AND an exam bucket — exactly as the export fans it out).
function targetBuckets(rec) {
  const out = [];
  const cl = normClass(rec.classLevel);
  if (cl && cl !== "unsorted" && CLASS_LABELS[cl] && rec.subject) out.push({ axis: "class", key: csKey(cl, rec.subject) });
  if (rec.scheme && EXAM_OF[rec.scheme] && rec.subject) out.push({ axis: "exam", key: csKey(rec.scheme, rec.subject) });
  return out;
}

// ── Manifest (derived from all buckets) ─────────────────────────────────────
function topicSummary(arr) {
  const byTopic = {};
  arr.forEach((q) => { const t = q.topic || "General"; byTopic[t] = (byTopic[t] || 0) + 1; });
  return Object.entries(byTopic)
    .map(([name, count]) => ({ name, count, papers: Math.ceil(count / PAPER_SIZE) }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
function rebuildManifest() {
  const classMap = {};
  for (const key of listKeys("class")) {
    const [cls, subject] = key.split("__");
    const arr = readBucket("class", key);
    if (!arr.length) continue;
    (classMap[cls] ||= []).push({ key: subject, label: subjLabel(subject), count: arr.length, topics: topicSummary(arr) });
  }
  const classes = CLASS_ORDER.filter((c) => classMap[c]).map((c) => ({
    key: c, label: CLASS_LABELS[c], subjects: classMap[c].sort((a, b) => a.label.localeCompare(b.label)),
  }));

  const examMap = {};
  for (const key of listKeys("exam")) {
    const [scheme, subject] = key.split("__");
    const arr = readBucket("exam", key);
    if (!arr.length) continue;
    (examMap[scheme] ||= []).push({ key: subject, label: subjLabel(subject), count: arr.length, topics: topicSummary(arr) });
  }
  const examsByRegion = { national: [], international: [] };
  for (const region of Object.keys(EXAMS)) {
    for (const scheme of Object.keys(EXAMS[region])) {
      if (!examMap[scheme]) continue;
      examsByRegion[region].push({
        key: scheme, label: EXAMS[region][scheme], subjects: examMap[scheme].sort((a, b) => a.label.localeCompare(b.label)),
      });
    }
  }
  fs.writeFileSync(
    path.join(OUT_DIR, "manifest.js"),
    `${HEADER}\nexport const MANIFEST = ${JSON.stringify({ paperSize: PAPER_SIZE, classes, exams: examsByRegion })};\n`,
  );
}

// ── Mutations ───────────────────────────────────────────────────────────────
// Add many records (each a validated, full question object minus id). Appends to
// the end of each target bucket so paper order = insertion order, then rebuilds.
function addRecords(records) {
  const touched = new Set();
  const bucketCache = new Map(); // "axis:key" → arr
  const load = (axis, key) => {
    const ck = axis + ":" + key;
    if (!bucketCache.has(ck)) bucketCache.set(ck, readBucket(axis, key));
    return bucketCache.get(ck);
  };
  const ids = [];
  for (const rec of records) {
    const id = rec.id || newId();
    ids.push(id);
    const s = slim(id, { ...rec, classLevel: normClass(rec.classLevel) });
    for (const { axis, key } of targetBuckets(s)) {
      load(axis, key).push(s);
      touched.add(axis + ":" + key);
    }
  }
  for (const ck of touched) { const [axis, key] = ck.split(/:(.*)/); writeBucket(axis, key, bucketCache.get(ck)); }
  rebuildManifest();
  return ids;
}

// Find a record (the first matching slim) by id across every bucket.
function findRecord(id) {
  for (const axis of ["class", "exam"]) {
    for (const key of listKeys(axis)) {
      const arr = readBucket(axis, key);
      const hit = arr.find((q) => q.id === id);
      if (hit) return hit;
    }
  }
  return null;
}

function deleteRecord(id) {
  let removed = false;
  for (const axis of ["class", "exam"]) {
    for (const key of listKeys(axis)) {
      const arr = readBucket(axis, key);
      const next = arr.filter((q) => q.id !== id);
      if (next.length !== arr.length) { writeBucket(axis, key, next); removed = true; }
    }
  }
  if (removed) rebuildManifest();
  return removed;
}

// Update a record in place when its bucket placement is unchanged (preserves
// paper position); otherwise remove + re-add under the new placement.
function updateRecord(id, fields) {
  const cur = findRecord(id);
  if (!cur) return null;
  const merged = slim(id, { ...cur, ...fields, classLevel: normClass(fields.classLevel || cur.classLevel) });
  const before = new Set(targetBuckets(cur).map((b) => b.axis + ":" + b.key));
  const after = new Set(targetBuckets(merged).map((b) => b.axis + ":" + b.key));
  const sameBuckets = before.size === after.size && [...before].every((b) => after.has(b));

  if (sameBuckets) {
    for (const ck of after) {
      const [axis, key] = ck.split(/:(.*)/);
      const arr = readBucket(axis, key);
      const i = arr.findIndex((q) => q.id === id);
      if (i >= 0) arr[i] = merged; else arr.push(merged);
      writeBucket(axis, key, arr);
    }
    rebuildManifest();
  } else {
    deleteRecord(id);
    addRecords([{ ...merged }]); // merged already carries the id
  }
  return merged;
}

// ── Derived reads (drive the admin editor; all from disk, no Firestore) ─────
// Unique records by id (a question fanned into class+exam buckets counts once).
function allRecords() {
  const byId = new Map();
  for (const axis of ["class", "exam"]) {
    for (const key of listKeys(axis)) {
      for (const q of readBucket(axis, key)) if (!byId.has(q.id)) byId.set(q.id, q);
    }
  }
  return [...byId.values()];
}
function stats() {
  const byScheme = {};
  let total = 0;
  for (const x of allRecords()) {
    total++;
    const s = x.scheme || "?";
    (byScheme[s] = byScheme[s] || { total: 0, subjects: {} });
    byScheme[s].total++;
    const k = x.subject || "?";
    byScheme[s].subjects[k] = (byScheme[s].subjects[k] || 0) + 1;
  }
  return { total, byScheme };
}
function classes() {
  const map = {};
  for (const key of listKeys("class")) {
    const [cls, subject] = key.split("__");
    const n = readBucket("class", key).length;
    if (n) map[cls] = (map[cls] || 0) + n;
  }
  return CLASS_ORDER.filter((c) => map[c]).map((c) => ({ key: c, label: CLASS_LABELS[c], count: map[c] }));
}
function subjectsForClass(cls) {
  const out = [];
  for (const key of listKeys("class")) {
    const [c, subject] = key.split("__");
    if (c !== cls) continue;
    const n = readBucket("class", key).length;
    if (n) out.push({ key: subject, label: subjLabel(subject), count: n });
  }
  return out.sort((a, b) => a.label.localeCompare(b.label));
}
function topicsForClassSubject(cls, subject) {
  const arr = readBucket("class", csKey(cls, subject));
  const byTopic = {};
  arr.forEach((q) => { const t = (q.topic || "General"); byTopic[t] = (byTopic[t] || 0) + 1; });
  // Merge in curated/empty topics from the registry so they still show.
  for (const t of registryTopics(cls, subject)) if (byTopic[t.name] == null) byTopic[t.name] = 0;
  return Object.entries(byTopic)
    .map(([name, count]) => ({ topic: name, key: topicKeyOf(name), count, papers: Math.ceil(count / PAPER_SIZE) }))
    .sort((a, b) => a.topic.localeCompare(b.topic));
}
function papers(cls, subject, topic) {
  const arr = readBucket("class", csKey(cls, subject));
  const count = arr.filter((q) => (q.topic || "General") === topic).length;
  const n = Math.ceil(count / PAPER_SIZE);
  return { count, paperSize: PAPER_SIZE, papers: n, list: Array.from({ length: n }, (_, i) => ({ paper: i + 1, label: `Paper ${i + 1}` })) };
}
function listQuestions({ cls, subject, scheme, topic, paper }) {
  let arr;
  if (cls) arr = readBucket("class", csKey(cls, subject));
  else arr = readBucket("exam", csKey(scheme, subject));
  if (topic) arr = arr.filter((q) => (q.topic || "General") === topic);
  if (paper > 0) { const start = (paper - 1) * PAPER_SIZE; arr = arr.slice(start, start + PAPER_SIZE); }
  return arr;
}

// ── Topic registry (data/cbt/_topics.json) ──────────────────────────────────
const TOPICS_FILE = path.join(OUT_DIR, "_topics.json");
function readTopicReg() {
  try { return JSON.parse(fs.readFileSync(TOPICS_FILE, "utf8")) || {}; } catch (_) { return {}; }
}
function writeTopicReg(reg) { fs.writeFileSync(TOPICS_FILE, JSON.stringify(reg, null, 2) + "\n"); }
function registryTopics(cls, subject) {
  const reg = readTopicReg();
  const arr = reg[csKey(cls, subject)] || [];
  return arr.filter((t) => t && t.name).map((t) => ({ name: String(t.name).slice(0, 120), key: t.key || topicKeyOf(t.name) }));
}
// Topics shown in the admin picker = registry ∪ topics actually present in the bucket.
function topicList(cls, subject) {
  const seen = new Map();
  for (const t of registryTopics(cls, subject)) seen.set(t.key, t);
  for (const q of readBucket("class", csKey(cls, subject))) {
    const name = q.topic || "General"; const key = topicKeyOf(name);
    if (!seen.has(key)) seen.set(key, { name, key });
  }
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}
function addTopic(cls, subject, name) {
  const reg = readTopicReg();
  const k = csKey(cls, subject);
  const key = topicKeyOf(name);
  reg[k] = (reg[k] || []).filter((t) => (t.key || topicKeyOf(t.name)) !== key);
  reg[k].push({ name: String(name).slice(0, 120), key });
  writeTopicReg(reg);
  return topicList(cls, subject);
}
function removeTopic(cls, subject, name) {
  const reg = readTopicReg();
  const k = csKey(cls, subject);
  const key = topicKeyOf(name);
  reg[k] = (reg[k] || []).filter((t) => (t.key || topicKeyOf(t.name)) !== key);
  writeTopicReg(reg);
  return topicList(cls, subject);
}

module.exports = {
  OUT_DIR, PAPER_SIZE, CLASS_LABELS, normClass, subjLabel, topicKeyOf, csKey, EXAM_OF, newId, slim,
  readBucket, writeBucket, listKeys, targetBuckets, rebuildManifest,
  addRecords, updateRecord, deleteRecord, findRecord, allRecords,
  stats, classes, subjectsForClass, topicsForClassSubject, papers, listQuestions,
  topicList, addTopic, removeTopic,
};
